import fs from 'node:fs';
export const registry=JSON.parse(fs.readFileSync(new URL('../../registry/layout-composition.json',import.meta.url),'utf8'));
const C=registry.components,V=registry.valueIds;
export const slots=Object.fromEntries([1,2,3,4].flatMap(k=>[[`child${k}`,V['item'+k]],[`child${k}Width`,80],[`child${k}Height`,40]]));
export const buttons=Object.fromEntries(['primary','default','dashed','link'].flatMap((key,n)=>[[`child${n+1}`,V[key]],[`child${n+1}Width`,[88,87,88,55][n]],[`child${n+1}Height`,32]]));
export const row={col1:C.Col,col2:C.Col,col3:C.Col,col4:C.Col,childrenContent1:V.item1,childrenContent2:V.item2,childrenContent3:V.item3,childrenContent4:V.item4,span1:6,span2:6,span3:6,span4:6,height1:40,height2:40,height3:40,height4:40};
export const layout={header:C['Layout.Header'],content:C['Layout.Content'],footer:C['Layout.Footer'],sider:C['Layout.Sider'],hasSider:false,siderWidth:200,collapsedWidth:80,headerHeight:64,footerHeight:70};
export const splitter={panel1:C['Splitter.Panel'],panel2:V.panelTwo,size1:50,size2:50,resizable:true};
export const masonry=Object.fromEntries(Array.from({length:8},(_,n)=>[['item'+(n+1),V['item'+(n%4+1)]],['height'+(n+1),[100,60,140,80,120,90,160,70][n]]]).flat());
export function demo(component,props={},width=600,height=120,label=''){return{component,props,width,height,label};}
const d=demo;
export const groups={
 Divider:{description:'Separate article sections or divide inline actions.',defaults:{orientation:'horizontal',variant:'solid',size:'large'},masterSize:[600,49],matrix:[
 ['Orientation and line style',['solid','dashed','dotted'].flatMap(variant=>[d('Divider',{variant},740,49,variant+' · horizontal'),d('Divider',{variant,orientation:'vertical'},17,12.6,variant+' · vertical')])],
 ['Title placement',['start','center','end'].flatMap(titlePlacement=>[d('Divider',{children:'Text',titlePlacement},740,58,titlePlacement),d('Divider',{children:'Text',titlePlacement,plain:true},740,54,titlePlacement+' · plain')])],
 ['Spacing',['small','middle','large'].map(size=>d('Divider',{size},740,size==='small'?17:size==='middle'?33:49,'size = '+size))]],
 usage:[['Horizontal',[d('Divider',{},740,49),d('Divider',{children:'Text'},740,58),d('Divider',{children:'Text',titlePlacement:'start'},740,58)]],['Vertical',[d('Divider',{orientation:'vertical'},17,12.6)]],['Text and dashed line',[d('Divider',{children:'Text',dashed:true},740,58),d('Divider',{children:'Text',plain:true,titlePlacement:'end'},740,54)]],['Set the spacing size of the divider',['small','middle','large'].map(size=>d('Divider',{size},740,size==='small'?17:size==='middle'?33:49,size))]],
 api:[['children','ReactNode','Optional title; plain text is editable in the Inspector.'],['orientation / vertical','horizontal | vertical / boolean','Controls line direction.'],['titlePlacement','start | center | end','Title position on a horizontal line.'],['variant / dashed','solid | dashed | dotted / boolean','Rail treatment; dashed overrides variant.'],['plain / size','boolean / small | middle | large','Title typography / vertical spacing.']]},
 Flex:{description:'Align block-level children without adding child wrappers.',defaults:{...slots,gap:'0',align:'normal',justify:'normal'},masterSize:[740,80],matrix:[
 ['Orientation',[d('Flex',{...slots,gap:'16'},740,80,'horizontal'),d('Flex',{...slots,gap:'16',vertical:true},740,208,'vertical')]],
 ['Main-axis alignment',['flex-start','center','flex-end','space-between','space-around','space-evenly'].map(justify=>d('Flex',{...slots,justify,gap:'8'},740,80,justify))],
 ['Cross-axis alignment',['flex-start','center','flex-end','stretch','baseline'].map(align=>d('Flex',{...slots,child2Height:64,child3Height:80,align,gap:'16'},740,100,align))],
 ['Gap and wrapping',['small','middle','large','32'].map(gap=>d('Flex',{...buttons,gap,wrap:true},280,100,'gap '+gap+' · wrap'))]],
 usage:[['Basic',[d('Flex',{...slots,gap:'16'},740,80,'horizontal'),d('Flex',{...slots,vertical:true,gap:'16'},740,208,'vertical')]],['align',['flex-start','center','flex-end'].map(align=>d('Flex',{...buttons,align,justify:'space-between'},740,90,align))],['gap',['small','middle','large','32'].map(gap=>d('Flex',{...buttons,gap},740,48,gap))],['Wrap',[d('Flex',{...buttons,wrap:true,gap:'16'},240,112)]],['combination',[d('Flex',{child1:V.nestedFlex,child2:V.nestedFlex,child1Width:240,child2Width:240,child1Height:80,child2Height:80,justify:'space-between',align:'center',gap:'16'},740,140)]]],
 api:[['orientation / vertical','horizontal | vertical / boolean','Main axis of the container.'],['justify / align','CSS alignment values','Main-axis distribution / cross-axis alignment.'],['gap','number | small | middle | large','Preset gaps are 8 / 16 / 24 px.'],['wrap','boolean','Wrap children when the available main-axis size is exceeded.'],['children','ReactNode[]','child1–child4 are component-reference slots; dimensions are canvas layout inputs.']]},
 Grid:{description:'Compose responsive layouts with Row and Col on a 24-column grid.',component:'Row',defaults:row,masterSize:[740,40],matrix:[
 ['24-column spans',[d('Row',{...row,span1:12,span2:12,col3:'',col4:''},740,40,'12 + 12'),d('Row',{...row,span1:8,span2:8,span3:8,col4:''},740,40,'8 + 8 + 8'),d('Row',row,740,40,'6 + 6 + 6 + 6'),d('Row',{...row,span1:24,col2:'',col3:'',col4:''},740,40,'24')]],
 ['Gutter and offset',[0,8,16,24,32].map(gutter=>d('Row',{...row,gutter},740,40,'gutter '+gutter)).concat([d('Row',{...row,span1:6,offset1:6,span2:6,col3:'',col4:''},740,40,'offset 6')])],
 ['Justify',['start','center','end','space-between','space-around','space-evenly'].map(justify=>d('Row',{...row,span1:4,span2:4,col3:'',col4:'',justify},740,40,justify))],
 ['Align and order',['top','middle','bottom','stretch'].map(align=>d('Row',{...row,height2:80,height3:60,align,gutter:16},740,100,align)).concat([d('Row',{...row,order1:3,order2:2,order3:1,order4:0},740,40,'order 3 / 2 / 1 / 0'),d('Row',{...row,span1:12,span2:12,span3:12,span4:12,verticalGutter:16},740,96,'wrap + vertical gutter')])]],
 usage:[['Basic Grid',[d('Row',{...row,span1:12,span2:12,col3:'',col4:''},740,40),d('Row',{...row,span1:8,span2:8,span3:8,col4:''},740,40),d('Row',row,740,40)]],['Grid Gutter',[d('Row',{...row,gutter:16},740,40),d('Row',{...row,gutter:24,verticalGutter:16,span1:12,span2:12,span3:12,span4:12},740,96)]],['Column offset',[d('Row',{...row,span1:6,offset1:6,span2:6,col3:'',col4:''},740,40)]],['Sort',[d('Row',{...row,order1:3,order2:2,order3:1,order4:0},740,40)]],['Typesetting',['start','center','end','space-between','space-around','space-evenly'].map(justify=>d('Row',{...row,span1:4,span2:4,col3:'',col4:'',justify},740,40,justify))],['Alignment',['top','middle','bottom'].map(align=>d('Row',{...row,height2:80,align,gutter:16},740,100,align))],['Responsive',[d('Row',{...row},740,40,'desktop · span 6'),d('Row',{...row,span1:12,span2:12,span3:12,span4:12,verticalGutter:16},360,96,'compact viewport · span 12')]]],
 api:[['Row.gutter','number | [horizontal, vertical]','Column padding and row gap.'],['Row.justify / align','distribution / top | middle | bottom | stretch','Alignment of columns.'],['Col.span / offset / order','number','24-column units / leading units / ordering.'],['Col responsive props','xs · sm · md · lg · xl · xxl','Shown as explicit viewport snapshots; media-query switching runs in React.'],['Grid.useBreakpoint','hook','Grid is a documentation category, not a rendered Grid component.']]},
 Layout:{description:'Compose Header, Sider, Content, and Footer into page structure.',defaults:layout,masterSize:[740,300],matrix:[
 ['Structure',[d('Layout',layout,740,300,'Header / Content / Footer'),d('Layout',{...layout,hasSider:true},740,300,'Sider inside'),d('Layout',{...layout,hasSider:true,siderPlacement:'end'},740,300,'Sider end'),d('Layout',{...layout,hasSider:true,siderOutside:true},740,300,'Sider outside')]],
 ['Collapsed sider',[d('Layout',{...layout,hasSider:true,collapsed:false},740,300,'expanded · 200 px'),d('Layout',{...layout,hasSider:true,collapsed:true},740,300,'collapsed · 80 px'),d('Layout',{...layout,hasSider:true,collapsed:true,collapsedWidth:0},740,300,'collapsedWidth = 0')]],
 ['Sider theme',[d('Layout.Sider',{children:'',width:200,theme:'dark',collapsible:true},200,240,'dark'),d('Layout.Sider',{children:'',width:200,theme:'light',collapsible:true},200,240,'light')]]],
 usage:[['Basic Structure',[d('Layout',layout,740,300),d('Layout',{...layout,hasSider:true},740,300)]],['Header-Content-Footer',[d('Layout',layout,740,360)]],['Header-Sider',[d('Layout',{...layout,hasSider:true},740,360)]],['Header Sider 2',[d('Layout',{...layout,hasSider:true,siderOutside:true},740,360)]],['Sider',[d('Layout',{...layout,hasSider:true,siderOutside:true},740,300,'expanded'),d('Layout',{...layout,hasSider:true,siderOutside:true,collapsed:true},740,300,'collapsed')]],['Responsive',[d('Layout',{...layout,hasSider:true,collapsed:true,collapsedWidth:0},360,300,'narrow viewport')]],['Fixed Header',[d('Layout',layout,740,360,'sticky position is applied in React')]],['Fixed Sider',[d('Layout',{...layout,hasSider:true,siderOutside:true},740,360,'sticky position is applied in React')]]],
 api:[['Layout.hasSider','boolean','Row layout when a Sider is present.'],['Layout children','Header / Layout / Sider / Content / Footer','Reference slots preserve each nested component.'],['Sider.width / collapsedWidth','number | string','Default widths: 200 / 80 px.'],['Sider.collapsed / collapsible','boolean','Controlled collapsed snapshot / trigger visibility.'],['Sider.theme','dark | light','Sider and trigger colors.'],['breakpoint / callbacks','runtime','Responsive transitions and event callbacks run in React.']]},
 Masonry:{description:'Distribute items of different heights into the shortest columns.',defaults:{...masonry,columns:3,gutter:16,verticalGutter:16},masterSize:[740,380],matrix:[
 ['Columns',[2,3,4].map(columns=>d('Masonry',{...masonry,columns,gutter:16,verticalGutter:16},740,columns===2?520:380,'columns '+columns))],
 ['Gutter',[0,8,16,24].map(gutter=>d('Masonry',{...masonry,columns:3,gutter,verticalGutter:gutter},740,380,'gutter '+gutter))]],
 usage:[['Basic',[d('Masonry',{...masonry,columns:3,gutter:16,verticalGutter:16},740,380)]],['Responsive',[d('Masonry',{...masonry,columns:2,gutter:16,verticalGutter:16},360,520,'narrow viewport'),d('Masonry',{...masonry,columns:4,gutter:16,verticalGutter:16},740,340,'wide viewport')]],['Dynamic',[d('Masonry',{...masonry,item8:'',columns:3,gutter:16,verticalGutter:16},740,380,'before'),d('Masonry',{...masonry,columns:3,gutter:16,verticalGutter:16},740,380,'after adding an item')]]],
 api:[['columns','number | responsive map','Resolved column count for each viewport snapshot.'],['gutter','number | [horizontal, vertical]','Space between columns and items.'],['items','MasonryItem[]','Each item carries a real component reference and measured height.'],['itemRender / onLayoutChange / fresh','runtime','Rendering callbacks and relayout after content changes run in React.']]},
 Space:{description:'Set consistent spacing between inline children, or join controls with Space.Compact.',defaults:{...buttons,size:'small',align:'center'},masterSize:[740,48],matrix:[
 ['Size and orientation',['small','middle','large','32'].map(size=>d('Space',{...buttons,size},740,48,size)).concat([d('Space',{...buttons,size:'middle',vertical:true,align:'start'},740,176,'vertical')])],
 ['Alignment',['start','center','end','baseline'].map(align=>d('Space',{...slots,child2Height:64,child3Height:80,size:'middle',align},740,100,align))],
 ['Wrap and separator',[d('Space',{...buttons,size:'middle',wrap:true},240,100,'wrap'),d('Space',{...buttons,size:'large',separator:V.separator},740,48,'separator = Divider')]],
 ['Compact',['small','middle','large'].map(size=>d('Space.Compact',{...buttons,size},740,48,size)).concat([d('Space.Compact',{...buttons,vertical:true},120,125,'vertical')])]],
 usage:[['Basic Usage',[d('Space',{...buttons,size:'small'},740,48)]],['Vertical Space',[d('Space',{...slots,vertical:true,size:'middle',align:'start'},740,208)]],['Space Size',['small','middle','large','32'].map(size=>d('Space',{...buttons,size},740,48,size))],['Align',['start','center','end','baseline'].map(align=>d('Space',{...slots,child2Height:80,align,size:'middle'},740,100,align))],['Wrap',[d('Space',{...buttons,size:'middle',wrap:true},240,100)]],['separator',[d('Space',{...buttons,size:'large',separator:V.separator},740,48)]],['Compact Mode for form component',[d('Space.Compact',{child1:V.addon,child2:V.input,child3:V.primary,child1Width:80,child2Width:220,child3Width:88},740,32)]],['Button Compact Mode',[d('Space.Compact',buttons,740,32)]],['Vertical Compact Mode',[d('Space.Compact',{...buttons,vertical:true},120,125)]]],
 api:[['size','number | preset | pair','Small 8 / middle 16 / large 24 px; rowGap is the second axis.'],['orientation / vertical','horizontal | vertical / boolean','Inline or stacked children.'],['align / wrap','start | center | end | baseline / boolean','Item alignment and wrapping.'],['separator','ReactNode','Uses a Divider component reference.'],['Space.Compact','size / orientation / block','Shared border and outer corner treatment.'],['Space.Addon','children / size / disabled','An addon component for compact form groups.']]},
 Splitter:{description:'Resize adjacent panels horizontally or vertically.',defaults:splitter,masterSize:[740,240],matrix:[
 ['Orientation',[d('Splitter',splitter,740,240,'horizontal'),d('Splitter',{...splitter,vertical:true},740,240,'vertical')]],
 ['Sizes and panels',[d('Splitter',{...splitter,size1:30,size2:70},740,240,'30% / 70%'),d('Splitter',{...splitter,panel3:V.panelThree,size1:25,size2:50,size3:25},740,240,'25% / 50% / 25%')]],
 ['Resize and collapse',[d('Splitter',{...splitter,resizable:false},740,240,'resizable = false'),d('Splitter',{...splitter,collapsible:true},740,240,'collapsible'),d('Splitter',{...splitter,collapsible:true,collapsed:true},740,240,'collapsed'),d('Splitter',{...splitter,lazy:true},740,240,'lazy · released state')]]],
 usage:[['Basic',[d('Splitter',splitter,740,240)]],['Control mode',[d('Splitter',splitter,740,240,'enabled'),d('Splitter',{...splitter,resizable:false},740,240,'disabled resizing')]],['Vertical',[d('Splitter',{...splitter,vertical:true},740,240)]],['Collapsible',[d('Splitter',{...splitter,collapsible:true},740,240),d('Splitter',{...splitter,collapsible:true,collapsed:true},740,240)]],['Multiple panels',[d('Splitter',{...splitter,panel3:V.panelThree,size1:25,size2:50,size3:25},740,240)]],['Complex combination',[d('Splitter',{...splitter,panel2:V.nestedPanel},740,240)]],['Lazy',[d('Splitter',{...splitter,lazy:true},740,240,'snapshot after release')]],['Double-clicked reset',[d('Splitter',{...splitter,size1:30,size2:70},740,240,'resized'),d('Splitter',splitter,740,240,'reset to default')]]],
 api:[['orientation / vertical','horizontal | vertical / boolean','Panel arrangement.'],['children','Splitter.Panel[]','Only Panel component instances are accepted.'],['Panel.size / min / max','number | percentage','Controlled size and resize limits; examples use percentage slots.'],['Panel.resizable / collapsible','boolean','Resize permission and collapse affordance.'],['lazy / callbacks','runtime','Dragging, motion, constraints, and resize events execute in React.']]}
};
