import fs from 'node:fs';
const root=new URL('../../',import.meta.url), manifest=JSON.parse(fs.readFileSync(new URL('registry/layout-composition.json',root),'utf8'));
const common=`const i=pencil.input||{},W=pencil.width,H=pencil.height,nodes=[];
const refs=${JSON.stringify(manifest.components)};
const values=${JSON.stringify(manifest.values||{})};
const text=(name,content,x,y,width,height,color='#000000E0',size=14,weight='normal',align='left')=>({type:'text',name,content:String(content),x,y,width,height,textGrowth:'fixed-width-height',fontFamily:'Inter',fontSize:size,lineHeight:1.5714,fontWeight:weight,textAlign:align,fill:color});
const rect=(name,x,y,width,height,fill,radius=0)=>({type:'rectangle',name,x,y,width:Math.max(0,width),height:Math.max(0,height),fill,cornerRadius:radius});
const child=(ref,name,x,y,width,height,inputs)=>({type:'ref',ref,name,x,y,width,height,...(values[ref]||{}),...(inputs?{inputs:{...(values[ref]?.inputs||{}),...inputs}}:{})});
const slots=()=>Array.from({length:24},(_,n)=>n+1).filter(k=>i['child'+k]).map(k=>({k,ref:i['child'+k],w:Math.max(0,i['child'+k+'Width']??80),h:Math.max(0,i['child'+k+'Height']??32)}));
`;
const write=(name,inputs,body)=>fs.writeFileSync(new URL('canvas-components/'+name+'.js',root),`/**\n * @schema 2.11\n${inputs.map(x=>' * @input '+x).join('\n')}\n */\n${common}${body}\nreturn nodes;\n`);
const slotInputs=Array.from({length:24},(_,n)=>[`child${n+1}: ref`,`child${n+1}Width: number = 80`,`child${n+1}Height: number = 32`]).flat();
write('Layout.DemoItem',['children: string = "Content"','background: color = #1677FF','color: color = #FFFFFF'],`nodes.push(rect('Demo content surface',0,0,W,H,i.background||'#1677FF'));nodes.push(text('children',i.children||'',0,Math.max(0,(H-22)/2),W,22,i.color||'#FFFFFF',14,'normal','center'));`);
const dividerMetrics=JSON.parse(fs.readFileSync(new URL('scripts/fonts/divider-metrics.json',root),'utf8'));
write('Divider',['children: string = ""','orientation: enum("horizontal", "vertical") = "horizontal"','vertical: boolean = false','titlePlacement: enum("start", "center", "end", "left", "right") = "center"','variant: enum("solid", "dashed", "dotted") = "solid"','dashed: boolean = false','plain: boolean = false','size: enum("small", "middle", "large") = "large"','color: color = #0505050F','marginBlock: number = -1','labelWidth: number = -1','titleMargin: number = -1'],`const metrics=${JSON.stringify(dividerMetrics)};
const vertical=i.vertical||i.orientation==='vertical',variant=i.dashed?'dashed':i.variant||'solid',color=i.color||'#0505050F';
function rail(x,y,length){const step=variant==='dotted'?3:variant==='dashed'?6:Math.max(1,length),dash=variant==='dotted'?1:variant==='dashed'?3:length;for(let p=0;p<length;p+=step)nodes.push(rect('rail',vertical?x:x+p,vertical?y+p:y,vertical?1:Math.min(dash,length-p),vertical?Math.min(dash,length-p):1,color));}
if(vertical)rail(8,0,12.6);else{const label=i.children||'',fs=i.plain?14:16,margin=i.marginBlock>=0?i.marginBlock:i.size==='small'?8:i.size==='middle'?16:label?16:24,lineHeight=label?fs*1.5714:1,y=margin+lineHeight/2;
if(!label)rail(0,margin,W);else{const m=metrics[i.plain?400:500];let measured=0,previous='';for(const ch of Array.from(label)){measured+=(m.widths[ch]??(ch.codePointAt(0)>255?1:.6))+(m.pairs[previous+ch]||0);previous=ch;}const tw=Math.max(Math.ceil(measured*fs)+1,i.labelWidth>=0?i.labelWidth:0),space=tw+fs*2,rest=Math.max(0,W-space),p=i.titlePlacement||'center',start=p==='start'||p==='left'?(i.titleMargin>=0?i.titleMargin:rest*.05):p==='end'||p==='right'?(i.titleMargin>=0?rest-i.titleMargin:rest*.95):rest/2;rail(0,y, start);nodes.push({...text('children',label,start+fs,margin,tw,lineHeight,'#000000E0',fs,i.plain?'normal':'500','left'),textGrowth:'auto'});rail(start+space,y,W-start-space);}}`);
const flexBody=(space=false,compact=false)=>`const vertical=i.vertical||i.orientation==='vertical',items=slots(),preset={small:8,middle:16,medium:16,large:24},gap=${compact?'0':space?'preset[i.size]??Math.max(0,Number(i.size)||0)':'preset[i.gap]??Math.max(0,Number(i.gap)||0)'},crossGap=i.rowGap>=0?i.rowGap:gap,limit=vertical?H:W,lines=[[]];let used=0;
for(const a of items){${compact?"a.h=i.size==='small'?24:i.size==='large'?40:32;if(vertical||i.block)a.w=vertical?W:(W+items.length-1)/items.length;":''}const main=vertical?a.h:a.w;if(i.wrap&&lines.at(-1).length&&used+gap+main>limit){lines.push([]);used=0;}lines.at(-1).push(a);used+=main+(used?gap:0);}
let cross=0;for(const line of lines){let total=line.reduce((s,a)=>s+(vertical?a.h:a.w),0)+gap*Math.max(0,line.length-1),free=Math.max(0,limit-total),justify=i.justify||'start',step=gap,main=0;
if(justify==='center')main=free/2;else if(justify==='end'||justify==='flex-end')main=free;else if(justify==='space-between'&&line.length>1)step+=free/(line.length-1);else if(justify==='space-around'){step+=free/line.length;main=free/line.length/2;}else if(justify==='space-evenly'){step+=free/(line.length+1);main=free/(line.length+1);}
const maxCross=i.wrap?Math.max(...line.map(a=>vertical?a.w:a.h)):(vertical?W:H);
for(let index=0;index<line.length;index++){const a=line[index],align=i.align||'${space?'center':'normal'}';let cw=a.w,ch=a.h,offset=0;if(align==='stretch'||(vertical&&align==='normal')){if(vertical)cw=maxCross;else ch=maxCross;}else if(align==='center'||align==='middle')offset=(maxCross-(vertical?cw:ch))/2;else if(align==='end'||align==='flex-end'||align==='bottom')offset=maxCross-(vertical?cw:ch);
if(align==='baseline'&&!vertical)offset=Math.max(...line.map(b=>b.h/2+6))-ch/2-6;const x=vertical?cross+offset:main,y=vertical?main:cross+offset;
nodes.push(child(a.ref,'children['+(a.k-1)+']',x,y,cw,ch,${compact?"{size:i.size||'middle',compactOrientation:vertical?'vertical':'horizontal',compactPlacement:index===0?'start':index===line.length-1?'end':'middle'}":"undefined"}));main+=(vertical?ch:cw)+step${compact?'-1':''};
${space&&!compact?"if(i.separator&&index<line.length-1)nodes.push(child(i.separator,'separator',vertical?0:main-gap/2-8,vertical?main-gap/2-6.3:(H-12.6)/2,17,12.6));":''}
}cross+=maxCross+crossGap;}`;
write('Flex',['orientation: enum("horizontal", "vertical") = "horizontal"','vertical: boolean = false','justify: enum("normal", "flex-start", "center", "flex-end", "space-between", "space-around", "space-evenly") = "normal"','align: enum("normal", "flex-start", "center", "flex-end", "stretch", "baseline") = "normal"','gap: string = "0"','rowGap: number = -1','wrap: boolean = false',...slotInputs],flexBody());
write('Space',['orientation: enum("horizontal", "vertical") = "horizontal"','vertical: boolean = false','size: string = "small"','align: enum("start", "center", "end", "baseline") = "center"','wrap: boolean = false','rowGap: number = -1','separator: ref',...slotInputs],flexBody(true));
write('Space.Compact',['orientation: enum("horizontal", "vertical") = "horizontal"','vertical: boolean = false','size: enum("small", "middle", "large") = "middle"','block: boolean = false',...slotInputs],flexBody(true,true));
write('Space.Addon',['children: string = "https://"','size: enum("small", "middle", "large") = "middle"','disabled: boolean = false','variant: enum("outlined", "filled", "borderless") = "outlined"','status: enum("default", "error", "warning") = "default"','compactPlacement: enum("none", "start", "middle", "end") = "none"'],`const r=i.size==='small'?4:i.size==='large'?8:6,radius=i.compactPlacement==='start'?[r,0,0,r]:i.compactPlacement==='end'?[0,r,r,0]:i.compactPlacement==='middle'?0:r;nodes.push({...rect('Addon surface',0,0,W,H,i.variant==='borderless'?'#00000000':'#00000005',radius),stroke:i.variant==='borderless'||i.variant==='filled'?'#00000000':i.status==='error'?'#FF4D4F':i.status==='warning'?'#FAAD14':'#D9D9D9',strokeWidth:1});nodes.push(text('children',i.children||'',11,(H-22)/2,W-22,22,i.disabled?'#00000040':'#000000E0'));`);
write('Col',['span: number = 12','offset: number = 0','order: number = 0','push: number = 0','pull: number = 0','gutter: number = 0','children: string = ""','childrenContent: ref','background: color = #00000000','color: color = #FFFFFF','cornerRadius: number = 0'],`const x=i.gutter/2||0,w=Math.max(0,W-(i.gutter||0));if(i.childrenContent)nodes.push(child(i.childrenContent,'children',x,0,w,H));else if(i.children){nodes.push(rect('Content style',x,0,w,H,i.background||'#00000000',i.cornerRadius||0));nodes.push(text('children',i.children,x,Math.max(0,(H-22)/2),w,22,i.color||'#FFFFFF',14,'normal','center'));}`);
const colInputs=Array.from({length:24},(_,n)=>[`col${n+1}: ref`,`span${n+1}: number = 6`,`offset${n+1}: number = 0`,`order${n+1}: number = ${n}`,`height${n+1}: number = 40`,`children${n+1}: string = ""`,`childrenContent${n+1}: ref`,`background${n+1}: color = #00000000`,`color${n+1}: color = #FFFFFF`,`cornerRadius${n+1}: number = 0`]).flat();
write('Row',['gutter: number = 0','verticalGutter: number = 0','justify: enum("start", "center", "end", "space-between", "space-around", "space-evenly") = "start"','align: enum("top", "middle", "bottom", "stretch") = "top"','wrap: boolean = true',...colInputs],`const items=Array.from({length:24},(_,n)=>n+1).filter(k=>i['col'+k]&&i['span'+k]>0).map(k=>({k,span:Math.max(0,Math.min(24,i['span'+k]??6)),offset:Math.max(0,i['offset'+k]||0),order:i['order'+k]??k,h:i['height'+k]||40})).sort((a,b)=>a.order-b.order),lines=[[]];let units=0;
for(const a of items){if(i.wrap&&units+a.span+a.offset>24&&lines.at(-1).length){lines.push([]);units=0;}lines.at(-1).push(a);units+=a.span+a.offset;}let y=0;
for(const line of lines){const rh=lines.length===1?H:Math.max(...line.map(a=>a.h)),free=Math.max(0,24-line.reduce((s,a)=>s+a.span+a.offset,0))*W/24;let x=i.justify==='center'?free/2:i.justify==='end'?free:0,gap=0;if(i.justify==='space-between'&&line.length>1)gap=free/(line.length-1);if(i.justify==='space-around'){gap=free/line.length;x=gap/2;}if(i.justify==='space-evenly'){gap=free/(line.length+1);x=gap;}
for(const a of line){x+=a.offset*W/24;const h=i.align==='stretch'?rh:a.h,dy=i.align==='middle'?(rh-h)/2:i.align==='bottom'?rh-h:0;nodes.push(child(i['col'+a.k],'Col '+a.k,x,y+dy,a.span*W/24,h,{span:a.span,offset:a.offset,order:a.order,gutter:i.gutter||0,children:i['children'+a.k]||'',childrenContent:i['childrenContent'+a.k]||'',background:i['background'+a.k]||'#00000000',color:i['color'+a.k]||'#FFFFFF',cornerRadius:i['cornerRadius'+a.k]||0}));x+=a.span*W/24+gap;}y+=rh+(i.verticalGutter||0);}`);
for(const part of ['Header','Content','Footer'])write('Layout.'+part,['children: ref','background: color = '+(part==='Header'?'#001529':part==='Footer'?'#F5F5F5':'#00000000'),'paddingInline: number = '+(part==='Content'?0:50),'paddingBlock: number = '+(part==='Footer'?24:0)],`nodes.push(rect('${part} surface',0,0,W,H,i.background));if(i.children)nodes.push(child(i.children,'children',i.paddingInline||0,i.paddingBlock||0,Math.max(0,W-2*(i.paddingInline||0)),Math.max(0,H-2*(i.paddingBlock||0))));`);
write('Layout.Sider',['children: ref','collapsed: boolean = false','collapsible: boolean = false','width: number = 200','collapsedWidth: number = 80','theme: enum("dark", "light") = "dark"','reverseArrow: boolean = false','trigger: ref'],`const width=i.collapsed?i.collapsedWidth:i.width,dark=i.theme!=='light';nodes.push(rect('Sider surface',0,0,width,H,dark?'#001529':'#FFFFFF'));if(i.children&&width>0)nodes.push(child(i.children,'children',0,0,width,Math.max(0,H-(i.collapsible?48:0))));if(i.collapsible&&width>0){nodes.push(rect('trigger surface',0,H-48,width,48,dark?'#002140':'#FFFFFF'));const icon=i.trigger||refs[i.collapsed!==i.reverseArrow?'RightOutlined':'LeftOutlined'];if(icon)nodes.push(child(icon,'trigger',(width-14)/2,H-31,14,14,{fontSize:14,color:dark?'#FFFFFF':'#000000E0'}));}`);
write('Layout',['header: ref','content: ref','footer: ref','sider: ref','hasSider: boolean = false','siderOverlay: boolean = false','siderPlacement: enum("start", "end") = "start"','siderOutside: boolean = false','collapsed: boolean = false','siderWidth: number = 200','collapsedWidth: number = 80','headerHeight: number = 64','footerHeight: number = 70'],`nodes.push(rect('Layout surface',0,0,W,H,'#F5F5F5'));const sw=i.hasSider&&i.sider?(i.collapsed?i.collapsedWidth:i.siderWidth):0,hh=i.header?i.headerHeight:0,fh=i.footer?i.footerHeight:0,end=i.siderPlacement==='end',sx=end?W-(i.siderOverlay?0:sw):0,cx=sw&&!end&&!i.siderOverlay?sw:0,out=i.siderOutside;
if(i.header)nodes.push(child(i.header,'Header',out?cx:0,0,out?W-(i.siderOverlay?0:sw):W,hh));if(i.content)nodes.push(child(i.content,'Content',cx,hh,W-(i.siderOverlay?0:sw),Math.max(0,H-hh-fh)));if(i.footer)nodes.push(child(i.footer,'Footer',out?cx:0,H-fh,out?W-(i.siderOverlay?0:sw):W,fh));if(sw)nodes.push(child(i.sider,'Sider',sx,out?0:hh,sw,out?H:Math.max(0,H-hh-fh),{width:i.siderWidth,collapsedWidth:i.collapsedWidth,collapsed:!!i.collapsed}));`);
write('Splitter.Panel',['children: ref','size: string = "50%"','min: string = "0"','max: string = "100%"','resizable: boolean = true','collapsible: boolean = false'],`if(i.children&&W>0&&H>0)nodes.push(child(i.children,'children',0,0,W,H));`);
write('Splitter',['orientation: enum("horizontal", "vertical") = "horizontal"','vertical: boolean = false','panel1: ref','panel2: ref','panel3: ref','size1: number = 50','size2: number = 50','size3: number = 0','resizable: boolean = true','collapsed: boolean = false','collapsible: boolean = false','draggerIcon: ref','sceneEffect: string = ""'],`if(i.sceneEffect)nodes.push({...rect('Example shadow',0,0,W,H,'#FFFFFF'),effect:JSON.parse(i.sceneEffect)});const vertical=i.vertical||i.orientation==='vertical',items=[1,2,3].filter(k=>i['panel'+k]),sizes=items.map(k=>Math.max(0,i['size'+k]||0));if(i.collapsed&&sizes.length>1){sizes[1]+=sizes[0];sizes[0]=0;}const total=sizes.reduce((a,b)=>a+b,0)||1;let p=0;items.forEach((k,index)=>{const size=sizes[index]/total*(vertical?H:W);if(size>0)nodes.push(child(i['panel'+k],'Splitter.Panel '+k,vertical?0:p,vertical?p:0,vertical?W:size,vertical?size:H));p+=size;if(index<items.length-1&&i.resizable!==false){nodes.push(rect('split bar',vertical?0:p-1,vertical?p-1:0,vertical?W:2,vertical?2:H,'#0505050F'));nodes.push(rect('dragger',vertical?(W-20)/2:p-1,vertical?p-1:(H-20)/2,vertical?20:2,vertical?2:20,'#00000026',1));if(i.draggerIcon)nodes.push(child(i.draggerIcon,'draggerIcon',vertical?(W-14)/2:p-7,vertical?p-7:(H-14)/2,14,14));if(i.collapsible){const ref=refs[vertical?(i.collapsed?'DownOutlined':'UpOutlined'):(i.collapsed?'RightOutlined':'LeftOutlined')];nodes.push(child(ref,'collapse',vertical?(W-14)/2:Math.max(6,p-7),vertical?Math.max(6,p-20):(H-14)/2-24,14,14,{fontSize:14,color:'#00000073'}));}}});`);
write('Masonry',['columns: number = 3','gutter: number = 16','verticalGutter: number = 16',...Array.from({length:24},(_,n)=>[`item${n+1}: ref`,`column${n+1}: number = -1`,`height${n+1}: number = ${[100,60,140,80,120,90,160,70][n%8]}`]).flat()],`const count=Math.max(1,Math.floor(i.columns||3)),g=Math.max(0,i.gutter||0),cw=Math.max(0,(W-g*(count-1))/count),ys=Array(count).fill(0);for(let k=1;k<=24;k++){if(!i['item'+k])continue;const c=i['column'+k]>=0?Math.min(count-1,Math.floor(i['column'+k])):ys.indexOf(Math.min(...ys)),h=Math.max(1,i['height'+k]||80);nodes.push(child(i['item'+k],'items['+(k-1)+'].children',c*(cw+g),ys[c],cw,h));ys[c]+=h+(i.verticalGutter??g);}`);
write('Card.content',['children: ref','padding: number = 24','variant: enum("outlined", "borderless") = "outlined"'],`const p=Math.max(0,i.padding??24)+(i.variant==='borderless'?0:1);nodes.push({...rect('Card surface',0,0,W,H,'#FFFFFF',8),stroke:i.variant==='borderless'?'#00000000':'#F0F0F0',strokeWidth:1});if(i.children)nodes.push({type:'frame',name:'Card body',x:p,y:p,width:W-2*p,height:H-2*p,layout:'none',clip:true,cornerRadius:Math.max(0,8-p),children:[child(i.children,'children',0,0,W-2*p,H-2*p)]});`);
console.log('Generated Layout scripts with real nested references');
