import fs from 'node:fs';
const root=new URL('../../',import.meta.url), manifest=JSON.parse(fs.readFileSync(new URL('registry/layout-composition.json',root),'utf8'));
const common=`const i=pencil.input||{},W=pencil.width,H=pencil.height,nodes=[];
const refs=${JSON.stringify(manifest.components)};
const values=${JSON.stringify(manifest.values||{})};
const text=(name,content,x,y,width,height,color='#000000E0',size=14,weight='normal',align='left')=>({type:'text',name,content:String(content),x,y,width,height,textGrowth:'fixed-width-height',fontFamily:'Inter',fontSize:size,lineHeight:1.5714,fontWeight:weight,textAlign:align,fill:color});
const rect=(name,x,y,width,height,fill,radius=0)=>({type:'rectangle',name,x,y,width:Math.max(0,width),height:Math.max(0,height),fill,cornerRadius:radius});
const child=(ref,name,x,y,width,height,inputs)=>({type:'ref',ref,name,x,y,width,height,...(values[ref]||{}),...(inputs?{inputs:{...(values[ref]?.inputs||{}),...inputs}}:{})});
`;
const write=(name,inputs,body)=>fs.writeFileSync(new URL('canvas-components/'+name+'.js',root),`/**\n * @schema 2.11\n${inputs.map(x=>' * @input '+x).join('\n')}\n */\n${common}${body}\nreturn nodes;\n`);
write('Layout.DemoItem',['children: string = "Content"','background: color = #1677FF','color: color = #FFFFFF'],`nodes.push(rect('Demo content surface',0,0,W,H,i.background||'#1677FF'));nodes.push(text('children',i.children||'',0,Math.max(0,(H-22)/2),W,22,i.color||'#FFFFFF',14,'normal','center'));`);
const dividerMetrics=JSON.parse(fs.readFileSync(new URL('scripts/fonts/divider-metrics.json',root),'utf8'));
write('Divider',['children: string = ""','orientation: enum("horizontal", "vertical") = "horizontal"','vertical: boolean = false','titlePlacement: enum("start", "center", "end", "left", "right") = "center"','variant: enum("solid", "dashed", "dotted") = "solid"','dashed: boolean = false','plain: boolean = false','size: enum("small", "middle", "large") = "large"','color: color = #0505050F','marginBlock: number = -1','labelWidth: number = -1','titleMargin: number = -1'],`const metrics=${JSON.stringify(dividerMetrics)};
const vertical=i.vertical||i.orientation==='vertical',variant=i.dashed?'dashed':i.variant||'solid',color=i.color||'#0505050F';
function rail(x,y,length){const step=variant==='dotted'?3:variant==='dashed'?6:Math.max(1,length),dash=variant==='dotted'?1:variant==='dashed'?3:length;for(let p=0;p<length;p+=step)nodes.push(rect('rail',vertical?x:x+p,vertical?y+p:y,vertical?1:Math.min(dash,length-p),vertical?Math.min(dash,length-p):1,color));}
if(vertical)rail(8,0,12.6);else{const label=i.children||'',fs=i.plain?14:16,margin=i.marginBlock>=0?i.marginBlock:i.size==='small'?8:i.size==='middle'?16:label?16:24,lineHeight=label?fs*1.5714:1,y=margin+lineHeight/2;
if(!label)rail(0,margin,W);else{const m=metrics[i.plain?400:500];let measured=0,previous='';for(const ch of Array.from(label)){measured+=(m.widths[ch]??(ch.codePointAt(0)>255?1:.6))+(m.pairs[previous+ch]||0);previous=ch;}const tw=Math.max(Math.ceil(measured*fs)+1,i.labelWidth>=0?i.labelWidth:0),space=tw+fs*2,rest=Math.max(0,W-space),p=i.titlePlacement||'center',start=p==='start'||p==='left'?(i.titleMargin>=0?i.titleMargin:rest*.05):p==='end'||p==='right'?(i.titleMargin>=0?rest-i.titleMargin:rest*.95):rest/2;rail(0,y, start);nodes.push({...text('children',label,start+fs,margin,tw,lineHeight,'#000000E0',fs,i.plain?'normal':'500','left'),textGrowth:'auto'});rail(start+space,y,W-start-space);}}`);
const flexBody=(space=false,compact=false)=>`const parse=(value,fallback)=>{if(value===undefined||value===null||value==='')return fallback;try{return typeof value==='string'?JSON.parse(value):value}catch{return fallback}};
const raw=parse(i.children,[]),items=(Array.isArray(raw)?raw:[]).map((a,index)=>typeof a==='string'?{k:index+1,ref:a,w:80,h:32}:{k:index+1,ref:a.ref||a.children,w:Math.max(0,a.width??80),h:Math.max(0,a.height??32)});
const vertical=${space?"i.orientation==='vertical'||i.vertical":"!!i.vertical"},preset={small:8,middle:16,medium:16,large:24},sizeValue=parse(${space?'i.size':'i.gap'},${space?'i.size':'i.gap'}),sizePair=Array.isArray(sizeValue)?sizeValue:[sizeValue,sizeValue],gap=${compact?'0':'preset[sizePair[0]]??Math.max(0,Number(sizePair[0])||0)'},crossGap=${compact?'0':'preset[sizePair[1]]??Math.max(0,Number(sizePair[1])||0)'},limit=vertical?H:W,lines=[[]];let used=0;
for(const a of items){${compact?"a.h=i.size==='small'?24:i.size==='large'?40:32;if(vertical)a.w=W;":''}const main=vertical?a.h:a.w;if(i.wrap&&lines.at(-1).length&&used+gap+main>limit){lines.push([]);used=0;}lines.at(-1).push(a);used+=main+(used?gap:0);}
let cross=0;for(const line of lines){let total=line.reduce((s,a)=>s+(vertical?a.h:a.w),0)+gap*Math.max(0,line.length-1),free=Math.max(0,limit-total),justify=i.justify||'start',step=gap,main=0;
if(justify==='center')main=free/2;else if(justify==='end'||justify==='flex-end')main=free;else if(justify==='space-between'&&line.length>1)step+=free/(line.length-1);else if(justify==='space-around'){step+=free/line.length;main=free/line.length/2;}else if(justify==='space-evenly'){step+=free/(line.length+1);main=free/(line.length+1);}
const maxCross=i.wrap?Math.max(...line.map(a=>vertical?a.w:a.h)):(vertical?W:H);
for(let index=0;index<line.length;index++){const a=line[index],align=i.align||${space?"(vertical?'start':'center')":"'normal'"};let cw=a.w,ch=a.h,offset=0;if(align==='stretch'||(vertical&&align==='normal')){if(vertical)cw=maxCross;else ch=maxCross;}else if(align==='center'||align==='middle')offset=(maxCross-(vertical?cw:ch))/2;else if(align==='end'||align==='flex-end'||align==='bottom')offset=maxCross-(vertical?cw:ch);
if(align==='baseline'&&!vertical)offset=Math.max(...line.map(b=>b.h/2+6))-ch/2-6;const x=vertical?cross+offset:main,y=vertical?main:cross+offset;
nodes.push(child(a.ref,'children['+(a.k-1)+']',x,y,cw,ch,${compact?"{size:i.size||'middle',compactOrientation:vertical?'vertical':'horizontal',compactPlacement:index===0?'start':index===line.length-1?'end':'middle'}":"undefined"}));main+=(vertical?ch:cw)+step${compact?'-1':''};
${space&&!compact?"if(i.separator&&index<line.length-1)nodes.push(child(i.separator,'separator',vertical?0:main-gap/2-8,vertical?main-gap/2-6.3:(H-12.6)/2,17,12.6));":''}
}cross+=maxCross+crossGap;}`;
write('Flex',['children: string = "[]"','vertical: boolean = false','justify: enum("normal", "flex-start", "center", "flex-end", "space-between", "space-around", "space-evenly") = "normal"','align: enum("normal", "flex-start", "center", "flex-end", "stretch", "baseline") = "normal"','flex: string = ""','gap: string = "0"','wrap: boolean = false','component: string = "div"'],flexBody());
write('Space',['children: string = "[]"','orientation: enum("horizontal", "vertical") = "horizontal"','vertical: boolean = false','size: string = "small"','align: enum("start", "center", "end", "baseline")','separator: ref','wrap: boolean = false','classNames: string = "{}"','styles: string = "{}"'],flexBody(true));
write('Space.Compact',['children: string = "[]"','orientation: enum("horizontal", "vertical") = "horizontal"','vertical: boolean = false','size: enum("small", "middle", "large") = "middle"','block: boolean = false'],flexBody(true,true));
write('Space.Addon',['children: string = "https://"','size: enum("small", "middle", "large") = "middle"','disabled: boolean = false','variant: enum("outlined", "filled", "borderless") = "outlined"','status: enum("default", "error", "warning") = "default"','compactPlacement: enum("none", "start", "middle", "end") = "none"'],`const r=i.size==='small'?4:i.size==='large'?8:6,radius=i.compactPlacement==='start'?[r,0,0,r]:i.compactPlacement==='end'?[0,r,r,0]:i.compactPlacement==='middle'?0:r;nodes.push({...rect('Addon surface',0,0,W,H,i.variant==='borderless'?'#00000000':'#00000005',radius),stroke:i.variant==='borderless'||i.variant==='filled'?'#00000000':i.status==='error'?'#FF4D4F':i.status==='warning'?'#FAAD14':'#D9D9D9',strokeWidth:1});nodes.push(text('children',i.children||'',11,(H-22)/2,W-22,22,i.disabled?'#00000040':'#000000E0'));`);
write('Col',['span: number = 12','offset: number = 0','order: number = 0','push: number = 0','pull: number = 0','gutter: number = 0','children: string = ""','childrenContent: ref','background: color = #00000000','color: color = #FFFFFF','cornerRadius: number = 0'],`const x=i.gutter/2||0,w=Math.max(0,W-(i.gutter||0));if(i.childrenContent)nodes.push(child(i.childrenContent,'children',x,0,w,H));else if(i.children){nodes.push(rect('Content style',x,0,w,H,i.background||'#00000000',i.cornerRadius||0));nodes.push(text('children',i.children,x,Math.max(0,(H-22)/2),w,22,i.color||'#FFFFFF',14,'normal','center'));}`);
write('Row',['children: string = "[]"','gutter: string = "0"','justify: string = "start"','align: string = "top"','wrap: boolean = true'],`const parse=(value,fallback)=>{if(value===undefined||value===null||value==='')return fallback;try{return typeof value==='string'?JSON.parse(value):value}catch{return fallback}};
const raw=parse(i.children,[]),items=(Array.isArray(raw)?raw:[]).map((a,index)=>({k:index+1,ref:typeof a==='string'?a:a.ref||a.childrenRef,span:Math.max(0,Math.min(24,Number(a.span??6))),offset:Math.max(0,Number(a.offset)||0),order:Number(a.order??index),h:Number(a.height)||40,data:typeof a==='string'?{}:a})).filter(a=>a.ref&&a.span>0).sort((a,b)=>a.order-b.order),gutterValue=parse(i.gutter,0),horizontal=Array.isArray(gutterValue)?Number(gutterValue[0])||0:Number(gutterValue)||0,verticalGap=Array.isArray(gutterValue)?Number(gutterValue[1])||0:0,lines=[[]];let units=0;
for(const a of items){if(i.wrap&&units+a.span+a.offset>24&&lines.at(-1).length){lines.push([]);units=0;}lines.at(-1).push(a);units+=a.span+a.offset;}let y=0;
for(const line of lines){const rh=lines.length===1?H:Math.max(...line.map(a=>a.h)),free=Math.max(0,24-line.reduce((s,a)=>s+a.span+a.offset,0))*W/24;let x=i.justify==='center'?free/2:i.justify==='end'?free:0,gap=0;if(i.justify==='space-between'&&line.length>1)gap=free/(line.length-1);if(i.justify==='space-around'){gap=free/line.length;x=gap/2;}if(i.justify==='space-evenly'){gap=free/(line.length+1);x=gap;}
for(const a of line){x+=a.offset*W/24;const h=i.align==='stretch'?rh:a.h,dy=i.align==='middle'?(rh-h)/2:i.align==='bottom'?rh-h:0,d=a.data||{};nodes.push(child(a.ref,'children['+(a.k-1)+']',x,y+dy,a.span*W/24,h,{span:a.span,offset:a.offset,order:a.order,gutter:horizontal,children:d.children||'',childrenContent:d.childrenContent||'',background:d.background||'#00000000',color:d.color||'#FFFFFF',cornerRadius:d.cornerRadius||0}));x+=a.span*W/24+gap;}y+=rh+verticalGap;}`);
for(const part of ['Header','Content','Footer'])write('Layout.'+part,['children: ref','background: color = '+(part==='Header'?'#001529':part==='Footer'?'#F5F5F5':'#00000000'),'paddingInline: number = '+(part==='Content'?0:50),'paddingBlock: number = '+(part==='Footer'?24:0)],`nodes.push(rect('${part} surface',0,0,W,H,i.background));if(i.children)nodes.push(child(i.children,'children',i.paddingInline||0,i.paddingBlock||0,Math.max(0,W-2*(i.paddingInline||0)),Math.max(0,H-2*(i.paddingBlock||0))));`);
write('Layout.Sider',['children: ref','collapsed: boolean = false','collapsible: boolean = false','width: number = 200','collapsedWidth: number = 80','theme: enum("dark", "light") = "dark"','reverseArrow: boolean = false','trigger: ref'],`const width=i.collapsed?i.collapsedWidth:i.width,dark=i.theme!=='light',zeroWidthTrigger=i.collapsible&&i.collapsedWidth===0;nodes.push(rect('Sider surface',0,0,width,H,dark?'#001529':'#FFFFFF'));if(i.children&&width>0)nodes.push(child(i.children,'children',0,0,width,Math.max(0,H-(i.collapsible&&!zeroWidthTrigger?48:0))));if(i.collapsible){const icon=i.trigger||refs[i.collapsed!==i.reverseArrow?'RightOutlined':'LeftOutlined'];if(zeroWidthTrigger){nodes.push(rect('zero-width trigger',width,48,40,40,dark?'#001529':'#FFFFFF',[0,8,8,0]));if(icon)nodes.push(child(icon,'trigger',width+10,58,20,20,{fontSize:20,color:dark?'#FFFFFF':'#000000E0'}));}else if(width>0){nodes.push(rect('trigger surface',0,H-48,width,48,dark?'#002140':'#FFFFFF'));if(icon)nodes.push(child(icon,'trigger',(width-14)/2,H-31,14,14,{fontSize:14,color:dark?'#FFFFFF':'#000000E0'}));}}`);
write('Layout',['header: ref','content: ref','footer: ref','sider: ref','hasSider: boolean = false','siderOverlay: boolean = false','siderPlacement: enum("start", "end") = "start"','siderOutside: boolean = false','collapsed: boolean = false','siderWidth: number = 200','collapsedWidth: number = 80','headerHeight: number = 64','footerHeight: number = 70'],`nodes.push(rect('Layout surface',0,0,W,H,'#F5F5F5'));const sw=i.hasSider&&i.sider?(i.collapsed?i.collapsedWidth:i.siderWidth):0,hh=i.header?i.headerHeight:0,fh=i.footer?i.footerHeight:0,end=i.siderPlacement==='end',sx=end?W-(i.siderOverlay?0:sw):0,cx=sw&&!end&&!i.siderOverlay?sw:0,out=i.siderOutside;
if(i.header)nodes.push(child(i.header,'Header',out?cx:0,0,out?W-(i.siderOverlay?0:sw):W,hh));if(i.content)nodes.push(child(i.content,'Content',cx,hh,W-(i.siderOverlay?0:sw),Math.max(0,H-hh-fh)));if(i.footer)nodes.push(child(i.footer,'Footer',out?cx:0,H-fh,out?W-(i.siderOverlay?0:sw):W,fh));if(sw)nodes.push(child(i.sider,'Sider',sx,out?0:hh,sw,out?H:Math.max(0,H-hh-fh),{width:i.siderWidth,collapsedWidth:i.collapsedWidth,collapsed:!!i.collapsed}));`);
write('Splitter.Panel',['children: ref','size: string = ""','defaultSize: string = ""','min: string = "0"','max: string = "100%"','resizable: boolean = true','collapsible: boolean = false','destroyOnHidden: boolean = false'],`if(i.children&&W>0&&H>0)nodes.push(child(i.children,'children',0,0,W,H));`);
write('Splitter.PanelContent',['children: string = ""','color: color = #00000073'],`nodes.push(text('Typography.Title',i.children||'',0,0,W,H,i.color||'#00000073',16,'600','center'));nodes[0].textAlignVertical='middle';nodes[0].lineHeight=1.5;`);
write('Splitter',['children: string = "[]"','orientation: enum("horizontal", "vertical") = "horizontal"','vertical: boolean = false','collapsible: string = "{}"','destroyOnHidden: boolean = false','draggerIcon: ref','onDraggerDoubleClick: string = ""','onResizeStart: string = ""','onResize: string = ""','onResizeEnd: string = ""','onCollapse: string = ""','lazy: boolean = false','classNames: string = "{}"','styles: string = "{}"'],`const parse=(value,fallback)=>{if(value===undefined||value===null||value==='')return fallback;try{return typeof value==='string'?JSON.parse(value):value}catch{return fallback}};
const semanticStyles=parse(i.styles,{}),sceneEffect=semanticStyles.sceneEffect,rootStyle=semanticStyles.root||{},draggerStyle=semanticStyles.dragger?.default||semanticStyles.dragger||{},rootFill=rootStyle.backgroundColor||'#FFFFFF',rootBorder=Math.max(0,Number(rootStyle.borderWidth)||0),borderColor=rootStyle.borderColor||'#D9D9D9',dashed=rootStyle.borderStyle==='dashed';
if(sceneEffect||rootStyle.backgroundColor||rootBorder)nodes.push({...rect('Splitter root style',0,0,W,H,rootFill),stroke:rootBorder&&!dashed?borderColor:'#00000000',strokeWidth:rootBorder&&!dashed?rootBorder:0,effect:sceneEffect?(typeof sceneEffect==='string'?JSON.parse(sceneEffect):sceneEffect):undefined});
if(rootBorder&&dashed){for(let x=0;x<W;x+=8){nodes.push(rect('Top border dash',x,0,Math.min(4,W-x),rootBorder,borderColor));nodes.push(rect('Bottom border dash',x,H-rootBorder,Math.min(4,W-x),rootBorder,borderColor));}for(let y=8;y<H-8;y+=8){nodes.push(rect('Left border dash',0,y,rootBorder,Math.min(4,H-y),borderColor));nodes.push(rect('Right border dash',W-rootBorder,y,rootBorder,Math.min(4,H-y),borderColor));}}
const globalCollapsible=parse(i.collapsible,{}),globalIcons=globalCollapsible.icon||{},raw=parse(i.children,[]),items=Array.isArray(raw)?raw:[],vertical=i.orientation==='vertical'||i.vertical;
const normalizeCollapsible=value=>value&&typeof value==='object'?{start:!!value.start,end:!!value.end,showCollapsibleIcon:value.showCollapsibleIcon===undefined?'auto':value.showCollapsibleIcon}:{start:!!value,end:!!value,showCollapsibleIcon:'auto'};
const getShowMode=(first,second)=>{if(first.collapsible&&second.collapsible){if(first.mode===true||second.mode===true)return true;if(first.mode==='auto'||second.mode==='auto')return'auto';return false;}return first.collapsible?first.mode:second.collapsible?second.mode:false;};
const numericSize=value=>{const number=parseFloat(value);return Number.isFinite(number)?Math.max(0,number):null},rawSizes=items.map(a=>numericSize(a.size??a.defaultSize)),specified=rawSizes.reduce((sum,size)=>sum+(size??0),0),missing=rawSizes.filter(size=>size===null).length,remaining=Math.max(0,100-specified),fallback=missing?(remaining>0?remaining/missing:1):0,sizes=rawSizes.map(size=>size??fallback),total=sizes.reduce((a,b)=>a+b,0)||1,axis=vertical?H:W,pixelSizes=sizes.map(size=>size/total*axis),barPositions=[];let cursor=0;
items.forEach((a,index)=>{const size=pixelSizes[index];if(size>0&&a.ref)nodes.push(child(a.ref,'children['+index+']',vertical?0:cursor,vertical?cursor:0,vertical?W:size,vertical?size:H));cursor+=size;barPositions[index]=cursor;});
items.slice(0,-1).forEach((a,index)=>{const size=pixelSizes[index],p=barPositions[index];
const next=items[index+1],nextSize=pixelSizes[index+1],prevCollapse=normalizeCollapsible(a.collapsible),nextCollapse=normalizeCollapsible(next.collapsible),resizable=a.resizable!==false&&next.resizable!==false&&(size!==0||!a.min)&&(nextSize!==0||!next.min);
nodes.push(rect('split bar',vertical?0:p-1,vertical?p-1:0,vertical?W:2,vertical?2:H,'#0505050F'));
if(resizable){nodes.push(rect('dragger',vertical?(W-20)/2:p-1,vertical?p-1:(H-20)/2,vertical?20:2,vertical?2:20,draggerStyle.backgroundColor||'#00000026',1));if(i.draggerIcon)nodes.push(child(i.draggerIcon,'draggerIcon',vertical?(W-14)/2:p-7,vertical?p-7:(H-14)/2,14,14));}
const prevEndCollapsible=prevCollapse.end&&size>0,nextStartExpandable=nextCollapse.start&&nextSize===0&&size>0,startCollapsible=prevEndCollapsible||nextStartExpandable;
const nextStartCollapsible=nextCollapse.start&&nextSize>0,prevEndExpandable=prevCollapse.end&&size===0&&nextSize>0,endCollapsible=nextStartCollapsible||prevEndExpandable;
const startMode=getShowMode({collapsible:prevEndCollapsible,mode:prevCollapse.showCollapsibleIcon},{collapsible:nextStartExpandable,mode:nextCollapse.showCollapsibleIcon}),endMode=getShowMode({collapsible:nextStartCollapsible,mode:nextCollapse.showCollapsibleIcon},{collapsible:prevEndExpandable,mode:prevCollapse.showCollapsibleIcon});
const addCollapse=(direction,enabled,mode)=>{if(!enabled||mode!==true)return;const custom=globalIcons[direction],ref=custom||refs[vertical?(direction==='start'?'UpOutlined':'DownOutlined'):(direction==='start'?'LeftOutlined':'RightOutlined')],customized=!!custom,bw=vertical?24:12,bh=vertical?12:24,bx=vertical?(W-bw)/2:direction==='start'?p-15:p+3,by=vertical?(direction==='start'?p-15:p+3):(H-bh)/2;if(!customized)nodes.push(rect('collapse '+direction+' surface',bx,by,bw,bh,'#0000000F',2));if(ref)nodes.push(child(ref,'collapse '+direction,bx+(bw-12)/2,by+(bh-12)/2,12,12,{fontSize:12,color:'#000000E0'}));};
addCollapse('start',startCollapsible,startMode);addCollapse('end',endCollapsible,endMode);
});`);
write('Masonry',['columns: string = "3"','gutter: string = "16"','items: string = "[]"','itemRender: ref','onLayoutChange: string = ""','classNames: string = "{}"','styles: string = "{}"','fresh: boolean = false'],`const parse=(value,fallback)=>{if(value===undefined||value===null||value==='')return fallback;try{return typeof value==='string'?JSON.parse(value):value}catch{return value}};
const responsive=(value,fallback)=>{if(typeof value==='number')return value;if(!value||typeof value!=='object')return Number(value)||fallback;const points=[['xxxl',2000],['xxl',1600],['xl',1200],['lg',992],['md',768],['sm',576],['xs',0]];for(const [key,min] of points)if(W>=min&&value[key]!=null)return Number(value[key])||fallback;return fallback};
const columns=Math.max(1,Math.floor(responsive(parse(i.columns,3),3))),gutterValue=parse(i.gutter,16),horizontal=Array.isArray(gutterValue)?responsive(gutterValue[0],16):responsive(gutterValue,16),vertical=Array.isArray(gutterValue)?responsive(gutterValue[1],horizontal):horizontal,g=Math.max(0,horizontal),vg=Math.max(0,vertical),cw=Math.max(0,(W-g*(columns-1))/columns),ys=Array(columns).fill(0);
const parsedItems=parse(i.items,[]),items=Array.isArray(parsedItems)?parsedItems:[];
items.forEach((item,index)=>{const requested=Number(item?.column),column=Number.isFinite(requested)&&requested>=0?Math.min(columns-1,Math.floor(requested)):ys.indexOf(Math.min(...ys)),dataHeight=typeof item?.data==='number'?item.data:undefined,h=Math.max(1,Number(item?.height??dataHeight??80)||80),content=item?.children||i.itemRender,x=column*(cw+g),y=ys[column];if(content){const resolved=parse(content,content);if(resolved&&typeof resolved==='object')nodes.push({...resolved,name:resolved.name||'items['+index+'].children',x,y,width:cw,height:h});else nodes.push(child(resolved,'items['+index+'].children',x,y,cw,h,{data:typeof item?.data==='string'?item.data:JSON.stringify(item?.data??''),index}));}ys[column]+=h+vg;});`);
write('Card.content',['title: string = ""','extra: string = ""','children: string = ""','cover: string = ""','padding: number = -1','size: enum("default", "small") = "default"','variant: enum("outlined", "borderless") = "outlined"','styles: string = "{}"'],`const parse=value=>{if(value===undefined||value===null||value==='')return undefined;try{return typeof value==='string'?JSON.parse(value):value}catch{return value}};const small=i.size==='small',basePadding=i.padding>=0?i.padding:(small?12:24),border=i.variant==='borderless'?0:1,p=Math.max(0,basePadding)+border;nodes.push({...rect('Card surface',0,0,W,H,'#FFFFFF',8),stroke:i.variant==='borderless'?'#00000000':'#F0F0F0',strokeWidth:1});const cover=parse(i.cover),coverH=cover&&typeof cover==='object'?Math.min(H,Math.max(0,Number(cover.height)||120)):0;if(coverH)nodes.push({...cover,name:cover.name||'cover',x:0,y:0,width:W,height:coverH});const headerH=i.title?(small?38:56):0;if(i.title){nodes.push(text('title',i.title,p,coverH,Math.max(0,W-2*p-(i.extra?72:0)),headerH,'#000000E0',small?14:16,'600'));if(i.extra)nodes.push(text('extra',i.extra,Math.max(p,W-p-64),coverH,64,headerH,'#1677FF',13,'normal','right'));nodes.push(rect('Header divider',0,coverH+headerH-1,W,1,'#F0F0F0'));}const bodyY=coverH+headerH,bw=Math.max(0,W-2*p),bh=Math.max(0,H-bodyY-2*p);if(i.children&&bh>0){const parsed=parse(i.children),content=values[i.children]?child(i.children,'children',0,0,bw,bh):parsed&&typeof parsed==='object'?{...parsed,name:parsed.name||'children',x:0,y:0,width:bw,height:bh}:text('children',i.children,0,Math.max(0,(bh-22)/2),bw,22,'#000000E0',14,'normal','center');nodes.push({type:'frame',name:'Card body',x:p,y:bodyY+p,width:bw,height:bh,layout:'none',clip:true,children:[content]});}`);
console.log('Generated Layout scripts with real nested references');
