const el = (component, props = {}) => ({ $component: component, props });
const button = label => el('Button', { children: label });
const content = '组件内容';
const options = [{ label: '设计', value: 'design' }, { label: '研发', value: 'dev' }, { label: '产品', value: 'pm' }];
const treeData = [{ title: '团队', key: '0', value: '0', children: [{ title: '设计', key: '0-0', value: '0-0' }, { title: '研发', key: '0-1', value: '0-1' }] }];
const items = [{ key: '1', label: '概览', title: '概览', children: '概览内容' }, { key: '2', label: '详情', title: '详情', children: '详情内容' }];
const children = [button('按钮一'), button('按钮二')];
export const fixtures = {
  Affix: { children: button('固定按钮') },
  Alert: { title: '提示标题', description: '提示说明', showIcon: true },
  Anchor: { affix: false, items: [{ key: 'intro', href: '#intro', title: '概览' }, { key: 'usage', href: '#usage', title: '使用方式' }] },
  App: { children: el('Alert', { title: '应用上下文', type: 'info' }) },
  AutoComplete: { options: options.map(o=>({value:o.value})), placeholder: '请输入', style: { width: 280 } },
  Avatar: { children: 'A' },
  BackTop: { visibilityHeight: 0, style: { position: 'relative', inset: 'auto' } },
  Badge: { count: 5, children: el('Avatar', { shape: 'square', children: 'A' }) },
  BorderBeam: { children: el('Card', { children: content, style: { width: 280 } }) },
  Breadcrumb: { items: [{ title: '首页' }, { title: '详情' }] },
  Button: { children: '按钮', type: 'primary' },
  Calendar: { fullscreen: false, defaultValue: { $date: '2026-09-16' } },
  Card: { title: '卡片标题', children: content },
  Carousel: { children: ['第一张', '第二张'].map(s=>el('div', {children:s, style:{height:120, background:'#364d79', color:'white', padding:32}})) },
  Cascader: { options: [{ value: 'zj', label: '浙江', children: [{ value: 'hz', label: '杭州' }] }], placeholder: '请选择' },
  Checkbox: { children: '选项' },
  Col: { span: 12, children: el('div', { children: '列', style: { background:'#e6f4ff', padding:16 } }) },
  Collapse: { items },
  ColorPicker: { defaultValue: '#1677ff', showText: true },
  DatePicker: { placeholder: '请选择日期' },
  Descriptions: { title:'用户信息', items:[{key:'name', label:'姓名', children:'张三'},{key:'role',label:'角色',children:'设计师'}] },
  Divider: { children: '分割线' },
  Drawer: { open:true, title:'编辑资料', children: content },
  Dropdown: { menu:{items:items.map(({key,label})=>({key,label}))}, children:button('操作菜单') },
  Empty: { description:'暂无数据' },
  Flex: { gap:8, children },
  FloatButton: { style:{ position:'relative', inset:'auto' } },
  Form: { layout:'vertical', children:[el('Form.Item',{label:'姓名', name:'name', rules:[{required:true,message:'请输入姓名'}], children:el('Input')}),el('Form.Item',{children:el('Button',{htmlType:'submit',type:'primary',children:'提交'})})] },
  Grid: {},
  Image: { width:160, height:100, preview:false, src:'data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="160" height="100"><rect width="160" height="100" fill="#e6f4ff"/><text x="55" y="55" fill="#1677ff">Image</text></svg>') },
  Input: { placeholder:'请输入内容' },
  InputNumber: { defaultValue:3, min:0, max:10 },
  Layout: { children:[el('Layout.Header',{children:'Header',style:{color:'white'}}),el('Layout.Content',{children:content,style:{padding:24}}),el('Layout.Footer',{children:'Footer'})] },
  List: { dataSource:['张三','李四'], renderItem:{$callback:'listItem'}, bordered:true },
  Masonry: { columns:3, gutter:8, items:[{key:'1',data:60},{key:'2',data:100},{key:'3',data:80}], itemRender:{$callback:'masonryItem'} },
  Mentions: { options:[{value:'张三',label:'张三'},{value:'李四',label:'李四'}], placeholder:'@成员' },
  Menu: { items:items.map(({key,label})=>({key,label})), defaultSelectedKeys:['1'] },
  Message: { content:'保存成功', type:'success', duration:0 },
  Modal: { open:true, title:'确认操作', children:'确认保存当前配置吗？', width:352 },
  Notification: { title:'操作成功', description:'配置已保存', duration:0 },
  Pagination: { defaultCurrent:1, total:50 },
  Popconfirm: { title:'确认删除？', children:button('删除') },
  Popover: { title:'提示标题', content:'提示内容', children:button('查看说明') },
  Progress: { percent:60 },
  QRCode: { value:'https://ant.design/', type:'svg', size:160 },
  Radio: { children:'选项' },
  Rate: { defaultValue:3 },
  Result: { status:'success', title:'提交成功', subTitle:'配置已保存' },
  Row: { gutter:8, children:[el('Col',{span:12,children:'左列'}),el('Col',{span:12,children:'右列'})] },
  Segmented: { options:['每日','每周','每月'] },
  Select: { options, placeholder:'请选择', style:{width:280} },
  Skeleton: { paragraph:{rows:3}, children:content },
  Slider: { defaultValue:40 },
  Space: { children },
  Spin: { children:el('div',{children:content,style:{height:80,padding:24}}) },
  Splitter: { style:{height:160}, children:[el('Splitter.Panel',{children:'面板一'}),el('Splitter.Panel',{children:'面板二'})] },
  Statistic: { title:'总用户数', value:12345 },
  Steps: { current:1, items:[{title:'已完成'},{title:'进行中'},{title:'待处理'}] },
  Switch: {},
  Table: { rowKey:'key', size:'small', columns:[{title:'姓名',dataIndex:'name'},{title:'角色',dataIndex:'role'}], dataSource:[{key:'1',name:'张三',role:'设计'},{key:'2',name:'李四',role:'研发'}], pagination:false },
  Tabs: { items },
  Tag: { children:'标签' },
  TimePicker: { placeholder:'请选择时间' },
  Timeline: { items:[{content:'创建项目'},{content:'开始开发'},{content:'部署完成',color:'green'}] },
  Tooltip: { title:'提示说明', children:button('悬停提示') },
  Tour: { open:true, steps:[{title:'欢迎使用',description:'了解工作区功能',target:null}] },
  Transfer: { dataSource:[{key:'1',title:'张三'},{key:'2',title:'李四'}], render:{$callback:'title'}, targetKeys:['2'], titles:['待选项','已选项'] },
  Tree: { treeData },
  TreeSelect: { treeData, placeholder:'选择节点', style:{width:280} },
  Typography: { children:'排版文本' },
  Upload: { beforeUpload:{$callback:'preventUpload'}, children:button('上传文件') },
  Watermark: { content:'Ant Design', children:el('div',{children:content,style:{height:160,padding:32}}) },
  'Alert.ErrorBoundary': { children:content },
  'Anchor.Link': { href:'#intro', title:'概览' },
  'Avatar.Group': { children:[el('Avatar',{children:'A'}),el('Avatar',{children:'B'})] },
  'Badge.Ribbon': { text:'推荐', children:el('Card',{children:content}) },
  'Breadcrumb.Item': { children:'首页' }, 'Breadcrumb.Separator': { children:'/' },
  'Button.Group': { children },
  'Card.Grid': { children:content }, 'Card.Meta': { title:'卡片标题',description:'卡片说明' },
  'Cascader.Panel': { options:[{value:'zj',label:'浙江',children:[{value:'hz',label:'杭州'}]}] },
  'Checkbox.Group': { options, defaultValue:['design'] },
  'Collapse.Panel': { header:'面板标题',children:content },
  'DatePicker.WeekPicker': {}, 'DatePicker.MonthPicker': {}, 'DatePicker.YearPicker': {}, 'DatePicker.RangePicker': {}, 'DatePicker.TimePicker': {}, 'DatePicker.QuarterPicker': {},
  'Descriptions.Item': { label:'姓名', children:'张三' },
  'Dropdown.Button': { menu:{items:items.map(({key,label})=>({key,label}))}, children:'操作菜单' },
  'FloatButton.Group': { style:{position:'relative',inset:'auto'}, children:[el('FloatButton'),el('FloatButton')] },
  'FloatButton.BackTop': { visibilityHeight:0, style:{position:'relative',inset:'auto'} },
  'Form.Item': { label:'姓名',name:'name',children:el('Input') },
  'Form.List': { name:'users',initialValue:[{name:'张三'}],children:{$callback:'formList'} },
  'Form.ErrorList': { errors:['请输入姓名'] },
  'Form.Provider': { children:el('Form',{children:el('Form.Item',{label:'姓名',children:el('Input')})}) },
  'Image.PreviewGroup': { children:el('Image',{width:160,src:'data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="160" height="100"><rect width="160" height="100" fill="#1677ff"/></svg>')}) },
  'Input.Group': { children:[el('Input',{placeholder:'姓名'}),el('Input',{placeholder:'邮箱'})] },
  'Input.Search': { placeholder:'搜索内容' },'Input.TextArea': { placeholder:'请输入内容' },'Input.Password': { placeholder:'请输入密码' },'Input.OTP': {},
  'Layout.Header': { children:'Header',style:{color:'white'} },'Layout.Footer': {children:'Footer'},'Layout.Content':{children:content},'Layout.Sider':{children:'Sider',style:{color:'white',minHeight:100}},
  'List.Item': { children:'列表项' },'List.Item.Meta':{title:'标题',description:'说明'},
  'Mentions.Option': { value:'design',children:'设计' },
  'Menu.Item': { children:'菜单项' },'Menu.SubMenu':{title:'子菜单',children:el('Menu.Item',{children:'菜单项'})},'Menu.Divider':{},
  'Radio.Group': { options },'Radio.Button':{children:'选项'},
  'Skeleton.Button':{},'Skeleton.Avatar':{},'Skeleton.Input':{},'Skeleton.Image':{},'Skeleton.Node':{},
  'Space.Compact':{children},'Space.Addon':{children:'https://'},
  'Splitter.Panel':{children:'面板'},
  'Statistic.Countdown':{title:'倒计时',value:4102444800000},'Statistic.Timer':{title:'计时器',type:'countdown',value:4102444800000},
  'Table.Column':{title:'姓名',dataIndex:'name'},'Table.ColumnGroup':{title:'用户',children:el('Table.Column',{title:'姓名',dataIndex:'name'})},
  'Tabs.TabPane':{tab:'概览',children:content},
  'Tag.CheckableTag':{checked:true,children:'选中标签'},'Tag.CheckableTagGroup':{options,value:['design']},
  'TimePicker.RangePicker':{},'Timeline.Item':{children:content},
  'Tooltip.UniqueProvider':{children:el('Tooltip',{title:'说明',children:button('提示')})},
  'Tree.DirectoryTree':{treeData},
  'Typography.Text':{children:'文本'},'Typography.Link':{children:'链接',href:'#intro'},'Typography.Title':{children:'标题',level:3},'Typography.Paragraph':{children:'这是正文段落。'},
  'Upload.Dragger':{beforeUpload:{$callback:'preventUpload'},children:'点击或拖拽文件上传'},
};

// Every state is an actual prop patch; no invented disabled/focus states for noninteractive components.
export const states = {
  Button:{default:{type:'default'},primary:{type:'primary'},dashed:{type:'dashed'},text:{type:'text'},link:{type:'link'},loading:{loading:true},disabled:{disabled:true},danger:{danger:true}},
  Alert:Object.fromEntries(['success','warning','error','info'].map(type=>[type,{type}])),
  Checkbox:{checked:{checked:true},unchecked:{checked:false},indeterminate:{indeterminate:true},disabled:{disabled:true}},
  Radio:{checked:{checked:true},unchecked:{checked:false},disabled:{disabled:true}},
  Switch:{checked:{checked:true},unchecked:{checked:false},disabled:{disabled:true},loading:{loading:true}},
  Collapse:{collapsed:{activeKey:[]},expanded:{activeKey:['1']}},
  Input:{default:{},focus:{autoFocus:true},filled:{variant:'filled'},disabled:{disabled:true},error:{status:'error'}},
  InputNumber:{default:{},'hover-controls':{controls:true},disabled:{disabled:true},error:{status:'error'}},
  Select:{default:{},open:{open:true},multiple:{mode:'multiple',value:['design','dev']},disabled:{disabled:true},error:{status:'error'}},
  TreeSelect:{default:{},open:{open:true},multiple:{multiple:true,value:['0-0']},disabled:{disabled:true},error:{status:'error'}},
  Cascader:{default:{},open:{open:true},disabled:{disabled:true},error:{status:'error'}},
  DatePicker:{default:{},open:{open:true},disabled:{disabled:true},error:{status:'error'}},
  TimePicker:{default:{},open:{open:true},disabled:{disabled:true}},
  Form:{default:{},disabled:{disabled:true},'required-error':{fields:[{name:['name'],errors:['请输入姓名']}]},success:{fields:[{name:['name'],value:'张三',errors:[]}]}},
  Empty:{default:{},'custom-description':{description:'没有符合条件的数据'}},
  Progress:Object.fromEntries(['normal','success','exception','active'].map(status=>[status,{status,...(status==='success'?{percent:100}:{})}])),
  Rate:{default:{},half:{allowHalf:true,value:2.5},disabled:{disabled:true}},
  Skeleton:{loading:{loading:true},loaded:{loading:false}},
  Slider:{default:{},disabled:{disabled:true},range:{range:true,value:[20,60]}},
  Spin:{spinning:{spinning:true},loaded:{spinning:false}},
  Table:{default:{},loading:{loading:true},empty:{dataSource:[]},'selected-row':{rowSelection:{selectedRowKeys:['1']}},pagination:{pagination:{pageSize:1}}},
  Tabs:{default:{},'active-tab':{activeKey:'2'},'disabled-tab':{items:[items[0],{...items[1],disabled:true}]}},
  Transfer:{default:{},selected:{selectedKeys:['1']},disabled:{disabled:true}},
  Tree:{default:{},expanded:{expandedKeys:['0']},checked:{checkable:true,checkedKeys:['0-0'],expandedKeys:['0']},disabled:{disabled:true}},
  Upload:{empty:{fileList:[]},uploading:{fileList:[{uid:'1',name:'文档.pdf',status:'uploading',percent:50}]},done:{fileList:[{uid:'1',name:'文档.pdf',status:'done'}]},error:{fileList:[{uid:'1',name:'文档.pdf',status:'error'}]},disabled:{disabled:true}},
};
for (const n of ['Modal','Drawer','Dropdown','Popover','Popconfirm','Tooltip','Tour']) states[n]={closed:{open:false},open:{open:true}};
export function getFixture(name, state='default') {
  if (!(name in fixtures)) throw new Error(`Missing fixture: ${name}`);
  if (state !== 'default' && !(state in (states[name] ?? {}))) throw new Error(`Unknown state: ${name}/${state}`);
  return {...fixtures[name],...(states[name]?.[state] ?? {})};
}
