/**
 * @schema 2.18
 * @input count: number = 5
 * @input dot: boolean = false
 * @input showZero: boolean = false
 * @input overflowCount: number = 99
 * @input color: color = #FF4D4F
 */
// Generated by scripts/generate-badge-canvas.mjs. Indicator only; the parent owns placement.
// GENERATED_DATA
const i=pencil.input||{},dot=!!i.dot,count=Number(i.count??5),overflow=Number(i.overflowCount??99);
if(!dot && (count<0 || count===0&&!i.showZero))return [];
const label=count>overflow?String(overflow)+'+':String(count);
const measure=s=>Array.from(s).reduce((v,c)=>v+(widths[c]??12),0);
const width=dot?6:label.length===1?20:Math.max(20,measure(label)+16),height=dot?6:20;
const nodes=[{type:'rectangle',name:'Badge surface',x:0,y:0,width,height,cornerRadius:height/2,fill:i.color||'#FF4D4F',effect:{type:'shadow',shadowType:'outer',color:'#FFFFFF',spread:1,blur:0,offset:{x:0,y:0}}}];
if(!dot)nodes.push({type:'text',name:'Badge count',content:label,x:0,y:0,width,height,textGrowth:'fixed-width-height',textAlign:'center',fontFamily:'Inter',fontSize:12,fontWeight:'400',lineHeight:20/12,fill:'#FFFFFF'});
return nodes;
