/**
 * @schema 2.11
 * @input shape: enum("circle", "square") = "circle"
 * @input type: enum("default", "primary") = "default"
 * @input icon: ref = "jn88O"
 * @input content: string = ""
 * @input disabled: boolean = false
 * @input showProgress: boolean = false
 * @input progress: number = 50
 * @input state: enum("normal", "hover", "active", "focus") = "normal"
 * @input groupPosition: enum("individual", "first", "middle", "last") = "individual"
 * @input background: string = ""
 * @input foreground: string = ""
 */
// Generated by scripts/generate-floatbutton-canvas.mjs. Edit the runtime template.
// GENERATED_DATA
const i=pencil.input||{},nodes=[];
const square=i.shape==='square',primary=i.type==='primary';
const style=styles[(primary?'primary':'default')+':'+(i.disabled?'disabled':i.state==='focus'?'normal':i.state||'normal')];
const valid=s=>/^#(?:[\da-f]{6}|[\da-f]{8})$/i.test(s||'');
const bg=valid(i.background)?i.background:style.bg,fg=valid(i.foreground)?i.foreground:style.color;
const content=square?String(i.content||''):'';
const hasIcon=!!i.icon;
const W=40,lineHeight=13.8;
const measure=s=>Array.from(s).reduce((v,c)=>v+(widths[c]??12),0);
const lines=[];let line='';
for(const word of content.split(/(\s+)/)){if(line&&measure(line+word)>38){lines.push(line.trim());line='';}for(const ch of word){if(line&&measure(line+ch)>38){lines.push(line);line='';}if(line||ch!==' ')line+=ch;}}
if(line)lines.push(line);
const iconSize=content?14:18;
const inner=(hasIcon?iconSize:0)+(hasIcon&&content?2:0)+lines.length*lineHeight;
const H=Math.max(40,inner+10);
let radius=square?8:20;
const grouped=i.groupPosition&&i.groupPosition!=='individual';
if(grouped&&square)radius=i.groupPosition==='first'?[8,8,0,0]:i.groupPosition==='last'?[0,0,8,8]:0;
const shadows=[{type:'shadow',shadowType:'outer',color:'#00000014',offset:{x:0,y:6},blur:16,spread:0},{type:'shadow',shadowType:'outer',color:'#0000001F',offset:{x:0,y:3},blur:6,spread:-4},{type:'shadow',shadowType:'outer',color:'#0000000D',offset:{x:0,y:9},blur:28,spread:8}];
nodes.push({type:'rectangle',name:'FloatButton surface',x:0,y:0,width:W,height:H,cornerRadius:radius,fill:bg,stroke:i.showProgress?'#F0F0F0':style.border,strokeWidth:i.showProgress?2:1,strokeAlignment:'inner',...(!grouped?{effect:shadows}:{})});
if(i.state==='focus'&&!i.disabled)nodes.push({type:'rectangle',name:'Keyboard focus ring',x:-4,y:-4,width:48,height:H+8,cornerRadius:square?12:24,fill:'#00000000',stroke:'#91CAFF',strokeWidth:3,strokeAlignment:'inner'});
if(i.showProgress){
 const percent=Math.max(0,Math.min(100,Number(i.progress)||0));
 const point=angle=>{const dx=Math.sin(angle),dy=-Math.cos(angle);if(!square)return[20+19*dx,20+19*dy];let lo=0,hi=30;for(let n=0;n<24;n++){const d=(lo+hi)/2,x=Math.abs(dx*d),y=Math.abs(dy*d),outside=Math.hypot(Math.max(0,x-12),Math.max(0,y-12))>7;if(outside)hi=d;else lo=d;}return[20+dx*lo,20+dy*lo];};
 if(percent>0){const count=Math.max(1,Math.ceil(percent*2));const pts=Array.from({length:count+1},(_,n)=>point(n/count*percent/100*Math.PI*2));nodes.push({type:'path',name:'BackTop progress',x:0,y:0,width:40,height:40,viewBox:[0,0,40,40],geometry:pts.map((p,n)=>(n?'L':'M')+p.join(' ')).join(' '),fill:'#00000000',stroke:'#1677FF',strokeWidth:2});}
}
let y=(H-inner)/2;
if(hasIcon)y+=iconSize+(content?2:0);
for(const text of lines){nodes.push({type:'text',name:'FloatButton content',content:text,x:1,y,width:38,height:lineHeight,textGrowth:'fixed-width-height',textAlign:'center',fontFamily:'Inter',fontSize:12,fontWeight:'400',lineHeight:1.15,fill:fg});y+=lineHeight;}
if(hasIcon)nodes.push({type:'ref',name:'icon',context:'prop:icon',...(iconValues[i.icon]||i.loading||i.state==='loading'?{scriptUri:'../canvas-components/Icon.js'}:{}),ref:iconValues[i.icon]?'antd-icon-live-origin':i.icon,x:(W-iconSize)/2,y:(H-inner)/2,width:iconSize,height:iconSize,inputs:{...(iconValues[i.icon]||{}),fontSize:iconSize,color:fg}});
return nodes;
