/**
 * @schema 2.18
 * @input component: enum("Text", "Title", "Paragraph", "Link") = "__DEFAULT_COMPONENT__"
 * @input content: string = "Ant Design 界面排版"
 * @input level: enum("1", "2", "3", "4", "5") = "1"
 * @input type: enum("default", "secondary", "success", "warning", "danger") = "default"
 * @input strong: boolean = false
 * @input italic: boolean = false
 * @input underline: boolean = false
 * @input delete: boolean = false
 * @input code: boolean = false
 * @input mark: boolean = false
 * @input keyboard: boolean = false
 * @input disabled: boolean = false
 * @input copyable: boolean = false
 * @input editable: boolean = false
 * @input copied: boolean = false
 * @input editIcon: enum("EditOutlined", "HighlightOutlined") = "EditOutlined"
 * @input copyIcon: enum("CopyOutlined", "SmileOutlined") = "CopyOutlined"
 * @input copiedIcon: enum("CheckOutlined", "SmileFilled") = "CheckOutlined"
 * @input enterIcon: enum("EnterOutlined", "CheckOutlined", "none") = "EnterOutlined"
 * @input editTrigger: enum("icon", "text", "both") = "icon"
 * @input symbol: string = "Expand"
 * @input editing: boolean = false
 * @input ellipsis: boolean = false
 * @input rows: number = 1
 * @input expandable: boolean = false
 * @input expanded: boolean = false
 * @input suffix: string = ""
 * @input actionsPlacement: enum("end", "start") = "end"
 * @input state: enum("normal", "hover", "active") = "normal"
 * @input theme: enum("light", "dark") = "light"
 * @input color: string = ""
 */
// Generated by scripts/generate-typography-canvas.mjs. Edit its runtime template.
// GENERATED_DATA
const i=pencil.input||{}, nodes=[];
const component=i.component||'Text', title=component==='Title', link=component==='Link';
const level=Math.max(1,Math.min(5,Number(i.level)||1));
const fs=title?[38,30,24,20,16][level-1]:14;
const lh=title?[46,38,32,28,24][level-1]:22;
const weight=title||i.strong?600:400, italic=!!i.italic;
const t=tokens[i.theme==='dark'?'dark':'light'];
const typeColor={secondary:t.colorTextDescription,success:t.colorSuccessText,warning:t.colorWarningText,danger:t.colorErrorText};
const operation=i.state==='hover'?t.colorLinkHover:i.state==='active'?t.colorLinkActive:t.colorLink;
const color=i.disabled?t.colorTextDisabled:/^#(?:[\da-f]{3}|[\da-f]{4}|[\da-f]{6}|[\da-f]{8})$/i.test(i.color||'')?i.color:typeColor[i.type]||(link?operation:t.colorText);
const editing=!!(i.editable&&i.editing);
const mono=!editing&&!!(i.code||i.keyboard), font=mono?'Roboto Mono':'Inter';
const textSize=editing?fs:fs*(i.code?.85:1)*(i.keyboard?.9:1);
const metric=metrics[[font,weight,italic?1:0].join(':')];
function measure(s){let w=0,prev='';for(const ch of Array.from(s)){w+=(metric.widths[ch]===undefined?(/\p{Mark}/u.test(ch)?0:ch.codePointAt(0)>255?1:.6):metric.widths[ch])+(metric.pairs[prev+ch]||0);prev=ch;}return w*textSize;}
const W=Math.max(1,Number(pencil.width)||320);
const H=Math.max(1,Number(pencil.height)||lh);
const raw=String(i.content??'Ant Design 界面排版').replace(/\r\n?/g,'\n');
const actions=[];
if(i.editable&&i.editTrigger!=='text')actions.push(i.editIcon||'EditOutlined');
if(i.copyable)actions.push(i.copied?(i.copiedIcon||'CheckOutlined'):(i.copyIcon||'CopyOutlined'));
const actionWidth=actions.length*(fs+4), start=i.actionsPlacement==='start';
const decoration=boxes[[fs,weight,italic?1:0,(i.code?1:0)+(i.mark?2:0)+(i.keyboard?4:0)].join(':')];
const edge=decoration.edge;
const available=Math.max(1,W-(editing?24:edge*2+(start?actionWidth:0)));
let lines=[];
for(const paragraph of raw.split('\n')){
  let line='';
  // Keep words intact where possible; CJK breaks between characters.
  const chunks=paragraph.match(/[\x21-\x2c\x2e-\x7e]+-?|-| +|[^\x21-\x7e ]/gu)||[''];
  for(const chunk of chunks){
    if(line&&measure(line+chunk)>available){lines.push(line.trimEnd());line='';}
    for(const ch of Array.from(chunk)){if(line&&measure(line+ch)>available){lines.push(line.trimEnd());line='';}if(line||ch!==' ')line+=ch;}
  }
  lines.push(line.trimEnd());
}
const maxRows=component==='Text'||component==='Link'?1:Math.max(1,Math.floor(Number(i.rows)||1));
const tail=String(i.suffix||'');
const collapsed=!!i.ellipsis&&!i.expanded&&!editing;
let truncated=collapsed&&(lines.length>maxRows||measure(lines[lines.length-1]||'')+actionWidth>available);
let expandLabel=truncated&&i.expandable?(i.symbol||'Expand'):i.expanded&&i.expandable?'Collapse':'';
const labelWidth=expandLabel?measure(expandLabel)+4:0;
if(collapsed){
 lines=lines.slice(0,maxRows);
 if(truncated){let last=Array.from(lines.pop()||'');while(last.length&&measure(last.join('')+'…'+tail)+actionWidth+labelWidth>available)last.pop();lines.push(last.join('').trimEnd()+'…'+tail);}
}
if((!collapsed||!truncated)&&tail)lines[lines.length-1]+=tail;
// Inline actions follow the last line, wrapping together when no room remains.
if(!start&&!truncated&&measure(lines[lines.length-1])+actionWidth+labelWidth>available)lines.push('');
function rect(name,x,y,w,h,fill,stroke,radius=0){nodes.push({type:'rectangle',name,x,y,width:Math.max(0,w),height:Math.max(0,h),fill,cornerRadius:radius,...(stroke?{stroke,strokeWidth:1,strokeAlignment:'inner'}:{})});}
function text(content,x,y,size=textSize,fill=color,name='Text'){nodes.push({type:'text',name,content,x,y,fontFamily:font,fontSize:size,fontWeight:String(weight),fontStyle:italic?'italic':'normal',lineHeight:lh/size,textGrowth:'auto',fill,underline:!!i.underline,strikethrough:!!i.delete});}
function icon(name,x,y,size,fill){for(const path of icons[name].paths)nodes.push({type:'path',name,x,y,width:size,height:size,viewBox:icons[name].viewBox,geometry:path,fill});}
rect('Typography surface',0,0,W,H,t.colorBgContainer);
if(i.editable&&i.editing){
 const height=Math.max(lh+10,Number(pencil.height)||lh+10);
 rect('Editing surface',0,0,W,height,t.colorBgContainer,t.colorPrimary,6);
 // Textarea interior: 11px inline padding, 4px block padding; confirmation at bottom right.
 for(let row=0;row<lines.length;row++)text(lines[row],12,4+row*lh);
 if(i.enterIcon!=='none')icon(i.enterIcon||'EnterOutlined',W-24,height-22,14,t.colorTextDescription);
 return nodes;
}
for(let row=0;row<lines.length;row++){
 const s=lines[row],y=row*lh,x=start&&row===0?actionWidth:0;
 const tw=measure(s);
 for(const box of decoration.boxes){
   const mark=box.kind==='mark',kbd=box.kind==='kbd';
   rect(mark?'Mark background':kbd?'Keyboard background':'Code background',x+box.x,y+box.y,tw+box.extra,box.height,mark?'#FFE58F':kbd?'#9696960F':'#9696961A',mark?null:'#64646433',mark?0:3);
   if(kbd)rect('Keyboard bottom border',x+box.x+1,y+box.y+box.height-2,tw+box.extra-2,1,'#64646433');
 }
 text(s,x+edge,y,textSize,i.mark&&!i.disabled?'#000000':color);
}
let ax=start?0:measure(lines[lines.length-1])+edge*2;
const ay=start?0:(lines.length-1)*lh;
if(expandLabel){text(expandLabel,ax+4,ay,textSize,operation,'Ellipsis action');ax+=labelWidth;}
// Ant icons inherit font size and align -0.125em from the text baseline.
const baselineOffset=boxes[[fs,weight,italic?1:0,0].join(':')].baseline;
for(const name of actions){
 const x=ax+(!raw?0:4);
 icon(name,x,ay+baselineOffset-fs*.875,fs,i.copied&&name===(i.copiedIcon||'CheckOutlined')?t.colorSuccessText:operation);
 ax+=fs+4;
}
return nodes;
