const json=JSON.stringify;
const ref=(ref,inputs={},width=160,height=32)=>({type:'ref',name:'Nested component',ref,inputs,width,height});
const button=(label,type='default')=>ref('DQZzq',{children:label,type,icon:'',size:'middle'},140,32);
const card=()=>ref('LSKNJ',{title:'Card title',extra:'',children:'Card content',variant:'outlined'},340,160);
const text=content=>ref('LG38Z',{content,component:'Text',editable:false,copyable:false},300,22);
const cross=(axes,make)=>{let rows=[{}];for(const [k,values]of Object.entries(axes))rows=rows.flatMap(r=>values.map(v=>({...r,[k]:v})));return rows.map(make)};
const sample=(label,inputs={},width=360,height=120,component,extra={})=>({label,inputs,width,height,component,...extra});
const group=(title,cols,samples)=>({title,cols,samples});
const sizes=['small','default','large'],bool=[false,true],shape=['circle','square'];
const avatarSize=s=>s==='small'?24:s==='large'?40:32;
const treeData=json([{key:'0',title:'Workspace',children:[{key:'0-0',title:'Design',children:[{key:'0-0-0',title:'Components'}]},{key:'0-1',title:'Engineering'},{key:'0-2',title:'Archive',disabled:true}]}]);
const items=json([{key:'1',label:'Panel 1',children:'Panel content 1'},{key:'2',label:'Panel 2',children:'Panel content 2'},{key:'3',label:'Panel 3',children:'Panel content 3'}]);
const records=json([{key:'1',name:'John Brown',age:32,address:'New York'},{key:'2',name:'Jim Green',age:42,address:'London'},{key:'3',name:'Joe Black',age:28,address:'Sydney'}]);
const columns=json([{title:'Name',dataIndex:'name'},{title:'Age',dataIndex:'age'},{title:'Address',dataIndex:'address'}]);
const photo='images/ant.design/c1f5bcc0f96aaa3c.png';
export const plan={
Avatar:[group('Size × Shape × Content',6,cross({size:sizes,shape,content:['Icon','Text']},o=>sample(`${o.size} · ${o.shape} · ${o.content}`,{size:o.size,shape:o.shape,icon:o.content==='Icon'?'UserOutlined':'',text:o.content==='Text'?'U':'',src:'',customSize:0},avatarSize(o.size),avatarSize(o.size)))),group('Text length × Gap',4,cross({text:['U','USER','ANT DESIGN'],gap:[2,8]},o=>sample(`${o.text} · gap ${o.gap}`,{...o,customSize:64,backgroundColor:'#F56A00'},64,64))),group('Avatar.Group · Size × Shape',6,cross({size:sizes,shape},o=>sample(`${o.size} · ${o.shape}`,o,avatarSize(o.size)*4-24,avatarSize(o.size),'Avatar.Group')))],
Badge:[group('Count × Size',6,cross({count:[5,99,100],size:['default','small']},o=>sample(`${o.count} · ${o.size}`,o,40,40))),group('Zero × Visibility / Dot × Color',4,[...cross({showZero:bool,size:['default','small']},o=>sample(`zero · ${o.size} · showZero ${o.showZero}`,{...o,count:0},40,40)),...cross({dot:bool,color:['#FF4D4F','#1677FF']},o=>sample(`${o.dot?'dot':'count'} · ${o.color}`,{...o,count:8},40,40))]),group('Status × Text',5,cross({status:['success','processing','default','error','warning'],text:['','Status text']},o=>sample(`${o.status} · ${o.text?'text':'dot'}`,o,240,22))),group('Badge.Ribbon · Placement × Color',3,cross({placement:['start','end'],color:['#1677FF','#52C41A','#722ED1']},o=>sample(`${o.placement} · ${o.color}`,{...o,text:'Featured',children:json({...card(),inputs:{title:'',extra:'',children:'Card content',styles:'{"body":{"padding":40}}'}})},440,160,'Badge.Ribbon')))],
Calendar:[group('Fullscreen × Mode × Week numbers',2,cross({fullscreen:bool,mode:['month','year'],showWeek:bool},o=>sample(`${o.fullscreen?'full':'card'} · ${o.mode} · week ${o.showWeek}`,{...o,value:'2026-09-19'},o.fullscreen?740:340,o.fullscreen?520:340)))],
Card:[group('Size × Variant × Loading',2,cross({size:['default','small'],variant:['outlined','borderless'],loading:bool},o=>sample(`${o.size} · ${o.variant} · ${o.loading?'loading':'content'}`,{...o,title:'Card title',children:'Card content',extra:'More',bordered:o.variant==='outlined'},720,180,undefined,{background:o.variant==='borderless'?'#F5F5F5':undefined}))),group('Card.Meta × Card.Grid',3,[sample('Meta · title + description',{title:'Europe Street beat',description:'www.instagram.com'},440,90,'Card.Meta'),sample('Meta · description only',{title:'',description:'Description'},440,90,'Card.Meta'),...bool.map(hoverable=>sample(`Grid · hoverable ${hoverable}`,{children:'Content',hoverable},300,100,'Card.Grid'))])],
Carousel:[group('Dot placement × Arrows',2,cross({dotPlacement:['top','bottom','start','end'],arrows:bool},o=>sample(`${o.dotPlacement} · arrows ${o.arrows}`,{...o,dots:true,children:'1|2|3|4'},720,160))),group('Initial slide × Indicators',2,cross({initialSlide:[0,2],dots:bool},o=>sample(`slide ${o.initialSlide+1} · dots ${o.dots}`,{...o,arrows:true},720,160)))],
Collapse:[group('Size × Surface × Expanded panels',2,cross({size:['small','middle','large'],ghost:bool,activeKey:['[]','["1","2"]']},o=>sample(`${o.size} · ${o.ghost?'ghost':'outlined'} · ${o.activeKey==='[]'?'closed':'expanded'}`,{...o,items},720,3*((o.size==='large'?57:o.size==='small'?38:46)+1)+(o.activeKey==='[]'?0:108)+1))),group('Expand icon placement × Disabled',2,cross({expandIconPlacement:['start','end'],collapsible:['header','disabled']},o=>sample(`${o.expandIconPlacement} · ${o.collapsible}`,{...o,items,activeKey:'[]'},720,142)))],
Descriptions:[group('Layout × Border × Size',2,cross({layout:['horizontal','vertical'],bordered:bool,size:['small','middle','large']},o=>sample(`${o.layout} · border ${o.bordered} · ${o.size}`,{...o,title:'User information',column:3,items:'Name:Zhou Maomao|Telephone:1810000000|Live:Hangzhou|Remark:None|Address:West Lake District|Status:Active'},740,260))),group('Columns × Colon',2,cross({column:[1,2,3],colon:bool},o=>sample(`${o.column} columns · colon ${o.colon}`,o,740,260)))],
Empty:[group('Image × Description × Action',3,cross({image:['default','simple'],description:['No data','No matching results'],action:bool},o=>sample(`${o.image} · ${o.description} · ${o.action?'action':'no action'}`,{image:o.image,description:o.description,children:o.action?json(button('Create now','primary')):''},460,210)))],
Image:[group('Image size × Preview',3,cross({size:[120,180,240],preview:['true','false']},o=>sample(`${o.size}px · preview ${o.preview}`,{src:photo,width:o.size,height:o.size,preview:o.preview},o.size,o.size))),group('Image.PreviewGroup · Two images × Size',2,[120,180].map(s=>sample(`${s}px × 2`,{children:json([0,1].map((n)=>({...ref('tTT7M',{src:photo,width:s,height:s},s,s),x:n*(s+16),y:0})))},s*2+16,s,'Image.PreviewGroup')))],
Listy:[group('Viewport × Row height',2,cross({height:[192,320],row:[40,64]},o=>sample(`height ${o.height} · row ${o.row}`,{height:o.height,items:json(Array.from({length:12},(_,n)=>({key:String(n),label:`List item ${n+1}`}))),styles:json({item:{height:o.row}})},720,o.height))),group('Item composition × Viewport',2,[192,320].map(height=>sample(`Card instances · ${height}px`,{height,itemRender:json(Array.from({length:4},(_,n)=>({...card(),height:88,inputs:{title:`Item ${n+1}`,children:'Item content',size:'small',extra:''}})))},720,height)))],
Popover:[group('Placement × Arrow',3,cross({placement:['top','bottom','left','right'],arrow:bool},o=>sample(`${o.placement} · arrow ${o.arrow}`,{...o,open:true,title:'Title',content:'Popover content'},480,200))),group('Title × Content',3,[sample('Title + content',{open:true,title:'Details',content:'Additional information'},480,200),sample('Content only',{open:true,title:'',content:'Content without a heading'},480,200),sample('Nested Button',{open:true,title:'Action',content:json(button('Continue','primary'))},480,200)])],
QRCode:[group('Status × Border',4,cross({status:['active','loading','expired','scanned'],bordered:bool},o=>sample(`${o.status} · border ${o.bordered}`,{...o,size:160},160,160))),group('Size × Error correction',4,cross({size:[120,200],errorLevel:['L','M','Q','H']},o=>sample(`${o.size}px · ${o.errorLevel}`,o,o.size,o.size)))],
Segmented:[group('Size × Shape × Disabled',3,cross({size:['small','middle','large'],shape:['default','round'],disabled:bool},o=>sample(`${o.size} · ${o.shape} · disabled ${o.disabled}`,{...o,options:'Daily|Weekly|Monthly',value:'Weekly'},Math.ceil(4+18*(o.size==='large'?16:14)*.53+3*(o.size==='small'?14:22)),o.size==='small'?24:o.size==='large'?40:32))),group('Orientation × Selection',3,cross({orientation:['horizontal','vertical'],value:['Daily','Weekly','Monthly']},o=>sample(`${o.orientation} · ${o.value}`,{...o,options:'Daily|Weekly|Monthly',block:true},o.orientation==='vertical'?180:420,o.orientation==='vertical'?88:32)))],
Statistic:[group('Precision × Loading',3,cross({precision:[0,1,2],loading:bool},o=>sample(`precision ${o.precision} · loading ${o.loading}`,{...o,title:'Account balance',value:'112893.56',prefix:'$',suffix:''},440,80))),group('Prefix × Suffix',3,[sample('Growth',{title:'Growth',value:'11.28',precision:2,prefix:'↑',suffix:'%',valueStyle:'{"color":"#3f8600"}'},440,80),sample('Capacity',{title:'Capacity',value:'93',suffix:'/ 100'},440,80),sample('Custom separators',{title:'Account balance',value:'112893.56',precision:2,decimalSeparator:',',groupSeparator:'.'},440,80)])],
Table:[group('Size × Border × Header',2,cross({size:['small','middle','large'],bordered:bool,showHeader:bool},o=>sample(`${o.size} · border ${o.bordered} · header ${o.showHeader}`,{...o,columns,dataSource:records,pagination:false},740,240))),group('Loading × Pagination',2,cross({loading:bool,pagination:bool},o=>sample(`loading ${o.loading} · pagination ${o.pagination}`,{...o,columns,dataSource:records,size:'middle'},740,260)))],
Tag:[group('Color × Variant × Closable',6,cross({color:['default','success','processing','warning','error','purple'],variant:['outlined','filled','solid'],closable:bool},o=>sample(`${o.color} · ${o.variant} · ${o.closable?'close':'plain'}`,{...o,children:o.color},14+o.color.length*7+(o.closable?16:0),22))),group('Tag.CheckableTag · Checked × Label',4,cross({checked:bool,children:['Movies','Books']},o=>sample(`${o.children} · checked ${o.checked}`,o,120,32,'Tag.CheckableTag')))],
Timeline:[group('Orientation × Mode × Variant',2,cross({orientation:['horizontal','vertical'],mode:['start','alternate','end'],variant:['outlined','filled']},o=>sample(`${o.orientation} · ${o.mode} · ${o.variant}`,{...o,items:json([{content:'Create',color:'green'},{content:'Review'},{content:'Release',color:'red'}])},740,o.orientation==='vertical'?180:120))),group('Order × Mode',2,cross({reverse:bool,mode:['start','alternate']},o=>sample(`${o.reverse?'reverse':'forward'} · ${o.mode}`,o,740,240)))],
Tooltip:[group('Placement × Arrow',3,cross({placement:['top','bottom','left','right'],arrow:bool},o=>sample(`${o.placement} · arrow ${o.arrow}`,{...o,open:true,title:'Prompt text'},480,180))),group('Color × Content',3,cross({color:['#000000D9','#1677FF','#722ED1'],title:['Prompt text','Additional information']},o=>sample(`${o.color} · ${o.title}`,{...o,open:true},480,180)))],
Tour:[group('Step × Type',2,cross({current:[0,1,2],type:['default','primary']},o=>sample(`step ${o.current+1} · ${o.type}`,{...o,open:true},620,210)))],
Tree:[group('Checkable × Lines × Disabled',2,cross({checkable:bool,showLine:bool,disabled:bool},o=>sample(`check ${o.checkable} · lines ${o.showLine} · disabled ${o.disabled}`,{...o,treeData,selectedKeys:'["0-0"]',checkedKeys:'["0-0-0"]',defaultExpandAll:true},720,180))),group('Block selection × Icons',2,cross({blockNode:bool,showIcon:bool},o=>sample(`block ${o.blockNode} · icons ${o.showIcon}`,{...o,treeData,selectedKeys:'["0-0"]'},720,180))),group('Tree.DirectoryTree · Selection × Disabled',2,cross({selectedKeys:['["0-0"]','["0-1"]'],disabled:bool},o=>sample(`${o.selectedKeys} · disabled ${o.disabled}`,{...o,treeData,defaultExpandAll:true},720,180,'Tree.DirectoryTree')))],
Alert:[group('Type × Variant × Icon',2,cross({type:['success','info','warning','error'],variant:['outlined','filled'],showIcon:bool},o=>sample(`${o.type} · ${o.variant} · icon ${o.showIcon}`,{...o,title:`${o.type} alert`,description:''},720,42))),group('Type × Description × Close',2,cross({type:['success','info','warning','error'],closable:bool},o=>sample(`${o.type} · description · close ${o.closable}`,{...o,title:'Alert title',description:'Additional information about this alert.',showIcon:true},720,90)))],
Drawer:[group('Placement × Loading',2,cross({placement:['left','right','top','bottom'],loading:bool},o=>sample(`${o.placement} · ${o.loading?'loading':'content'}`,{...o,open:true,title:'Drawer title',children:json(text('Drawer content')),width:320,height:240},740,320))),group('Mask × Close button',2,cross({mask:bool,closable:bool},o=>sample(`mask ${o.mask} · close ${o.closable}`,{...o,open:true,placement:'right',children:json(text('Drawer content'))},740,320))),group('Width × Side placement',2,cross({width:[378,560],placement:['left','right']},o=>sample(`${o.width}px · ${o.placement}`,{...o,open:true,title:'Drawer title',children:json(text('Drawer content')),mask:true},740,320)))],
Message:[group('Type × Content length',3,cross({type:['info','success','warning','error','loading'],long:bool},o=>sample(`${o.type} · ${o.long?'long':'short'}`,{type:o.type,content:o.long?'This is a message with more information.':'This is a message'},480,48)))],
Modal:[group('Position × Footer × Loading',2,cross({centered:bool,footer:bool,loading:bool},o=>sample(`${o.centered?'centered':'top'} · footer ${o.footer} · ${o.loading?'loading':'content'}`,{...o,open:true,width:520,title:'Modal title',children:json(text('Modal content'))},740,420))),group('Mask × Close button',2,cross({mask:bool,closable:bool},o=>sample(`mask ${o.mask} · close ${o.closable}`,{...o,open:true,centered:true,width:520},740,340))),group('Width × Action copy',2,cross({width:[420,680],localized:bool},o=>sample(`${o.width}px · ${o.localized?'localized':'default actions'}`,{open:true,width:o.width,centered:true,okText:o.localized?'确定':'OK',cancelText:o.localized?'取消':'Cancel'},740,340)))],
Notification:[group('Type × Progress × Actions',3,cross({type:['info','success','warning','error'],showProgress:bool,action:bool},o=>sample(`${o.type} · progress ${o.showProgress} · action ${o.action}`,{type:o.type,showProgress:o.showProgress,message:'Notification title',description:'Additional information about this notification.',actions:o.action?json(button('Confirm','primary')):''},480,170)))],
Popconfirm:[group('Placement × Cancel action',3,cross({placement:['top','bottom','left','right'],showCancel:bool},o=>sample(`${o.placement} · cancel ${o.showCancel}`,{...o,open:true,title:'Delete the task',description:'Are you sure to delete this task?'},420,140)))],
Progress:[group('Type × Status × Info',4,cross({type:['line','circle','dashboard'],status:['normal','active','success','exception'],showInfo:bool},o=>sample(`${o.type} · ${o.status} · info ${o.showInfo}`,{...o,percent:o.status==='success'?100:65},o.type==='line'?340:120,o.type==='line'?40:120))),group('Steps × Stroke caps',4,cross({steps:[0,5,10],strokeLinecap:['round','butt']},o=>sample(`steps ${o.steps} · ${o.strokeLinecap}`,{...o,type:'line',percent:60},340,40)))],
Result:[group('Status × Actions',2,cross({status:['success','info','warning','error','403','404','500'],action:bool},o=>sample(`${o.status} · ${o.action?'action':'no action'}`,{status:o.status,title:['403','404','500'].includes(o.status)?o.status:'Result title',subTitle:'Additional information about the result.',extra:o.action?json(button('Back home','primary')):''},740,400)))],
Skeleton:[group('Avatar × Round × Paragraph rows',2,cross({avatar:bool,round:bool,rows:[2,4]},o=>sample(`avatar ${o.avatar} · round ${o.round} · rows ${o.rows}`,{avatar:o.avatar,round:o.round,paragraph:json({rows:o.rows}),loading:true},720,200))),group('Skeleton.Button · Size × Shape',6,cross({size:sizes,shape:['default','circle','round']},o=>sample(`${o.size} · ${o.shape}`,o,o.shape==='circle'?avatarSize(o.size):120,avatarSize(o.size),'Skeleton.Button'))),group('Skeleton.Avatar · Size × Shape',6,cross({size:sizes,shape},o=>sample(`${o.size} · ${o.shape}`,o,avatarSize(o.size),avatarSize(o.size),'Skeleton.Avatar'))),group('Skeleton.Input · Size × Active',3,cross({size:sizes,active:bool},o=>sample(`${o.size} · active ${o.active}`,o,320,avatarSize(o.size),'Skeleton.Input')))],
Spin:[group('Size × Tip × Nested content',3,cross({size:sizes,tip:['','Loading...']},o=>sample(`${o.size} · ${o.tip?'tip':'no tip'}`,{...o,spinning:true,children:json(card())},460,200))),group('Spinning × Content',2,bool.map(spinning=>sample(`spinning ${spinning}`,{spinning,children:json(card()),tip:'Loading...'},720,200)))],
Watermark:[group('Rotation × Density',2,cross({rotate:[-22,0,22],gap:['[60,60]','[120,100]']},o=>sample(`rotate ${o.rotate} · gap ${o.gap}`,{...o,content:'Ant Design',children:json(card())},740,260))),group('Text × Font',2,cross({content:['Ant Design','Ant Design\nConfidential'],font:['{"fontSize":14,"color":"rgba(0,0,0,0.15)"}','{"fontSize":20,"color":"rgba(22,119,255,0.2)"}']},o=>sample(`${o.content.replace('\n',' / ')} · ${JSON.parse(o.font).fontSize}px`,{...o,children:json(card())},740,260)))],
Affix:[group('Offset edge × Offset distance',2,cross({edge:['top','bottom'],distance:[0,24]},o=>sample(`${o.edge} · offset ${o.distance}`,{children:json(button('Affixed button','primary')),offsetTop:o.edge==='top'?o.distance:0,offsetBottom:o.edge==='bottom'?o.distance:0},150,32,undefined,{scene:{edge:o.edge,distance:o.distance}})))],
App:[group('Children composition',2,[sample('Button child',{component:'div',children:json(button('Open message','primary'))},160,32),sample('Card child',{component:'div',children:json(card())},720,160),sample('Typography child',{component:'div',children:json(text('Application content'))},720,32)])],
BackTop:[group('Visibility threshold × Duration · runtime properties',4,cross({visibilityHeight:[200,400],duration:[300,600]},o=>sample(`threshold ${o.visibilityHeight} · ${o.duration}ms`,o,40,40)))],
BorderBeam:[group('Count × Color × Width',2,cross({count:[1,2],color:['#1677FF','#722ED1'],lineWidth:[1,2]},o=>sample(`count ${o.count} · ${o.color} · ${o.lineWidth}px`,{...o,children:json(card()),size:100},740,180)))],
};
