from pathlib import Path
p=Path('canvas-components')
common="""const i=pencil.input||{},W=Math.max(1,pencil.width),H=Math.max(1,pencil.height),nodes=[];
const text=(content,x,y,width,height=22,size=14,color='#000000E0',weight='400',align='left')=>({type:'text',name:String(content||'Text'),content:String(content||''),x,y,width,height,textGrowth:'fixed-width-height',fontFamily:'Inter',fontSize:size,fontWeight:weight,textAlign:align,textAlignVertical:'middle',lineHeight:1.5714,fill:color});
const box=(x,y,width,height,fill='#FFFFFF',radius=0,stroke='#00000000')=>({type:'rectangle',name:'Surface',x,y,width:Math.max(0,width),height:Math.max(0,height),fill,cornerRadius:radius,stroke,strokeWidth:stroke==='#00000000'?0:1,strokeAlignment:'inner'});
const icon=(name,x,y,size,color)=>({type:'ref',name:'Icon · '+name,ref:'antd-icon-live-origin',x,y,width:size,height:size,inputs:{name,fontSize:size,color}});
const button=(label,x,y,width=70,primary=false,size='middle')=>({type:'ref',name:'Button · '+label,ref:'DQZzq',x,y,width,height:size==='small'?24:32,inputs:{children:label,type:primary?'primary':'default',size}});
const child=(value,x,y,width,height)=>{if(!value)return;let n;try{n=JSON.parse(value)}catch{n={type:'text',name:'children',content:String(value),fontFamily:'Inter',fontSize:14,fill:'#000000E0',textGrowth:'fixed-width'}}if(n&&typeof n==='object')nodes.push({...n,x,y,width,height});};
"""
def write(name,props,body):
 (p/(name+'.js')).write_text('/**\n * @schema 2.18\n'+''.join(' * @input '+s+'\n' for s in props)+' */\n'+common+body+'\nreturn nodes;\n')
write('Alert',['title: string = "Success Text"','message: string = ""','description: string = ""','type: enum("success", "info", "warning", "error") = "success"','showIcon: boolean = false','closable: boolean = false','banner: boolean = false','variant: enum("outlined", "filled") = "outlined"','action: string = ""'],"""
const palettes={success:['#F6FFED','#B7EB8F','#52C41A','CheckCircle'],info:['#E6F4FF','#91CAFF','#1677FF','InfoCircle'],warning:['#FFFBE6','#FFE58F','#FAAD14','ExclamationCircle'],error:['#FFF2F0','#FFCCC7','#FF4D4F','CloseCircle']},c=palettes[i.type]||palettes.info,desc=!!i.description,sz=desc?24:14,pad=desc?20:12,hasIcon=i.showIcon||i.banner,x=pad+(hasIcon?sz+12:0),actionW=i.action?120:0;
nodes.push(box(0,0,W,H,c[0],i.banner?0:8,i.variant==='filled'||i.banner?'#00000000':c[1]));if(hasIcon)nodes.push(icon(c[3]+(desc?'Outlined':'Filled'),pad,desc?20:(H-sz)/2,sz,c[2]));
nodes.push(text(i.title||i.message,x,desc?12:0,W-x-pad-(i.closable?20:0)-actionW,desc?28:H,desc?16:14));if(desc)nodes.push({...text(i.description,x,42,W-x-pad-actionW,H-50),textAlignVertical:'top'});if(i.closable)nodes.push(icon('CloseOutlined',W-24,desc?16:(H-12)/2,12,'#00000073'));if(i.action)child(i.action,W-actionW-28,(H-32)/2,actionW,32);
""")
write('Message',['content: string = "This is a message"','type: enum("info", "success", "warning", "error", "loading") = "info"','duration: number = 3'],"""
const kinds={info:['InfoCircleFilled','#1677FF'],success:['CheckCircleFilled','#52C41A'],warning:['ExclamationCircleFilled','#FAAD14'],error:['CloseCircleFilled','#FF4D4F'],loading:['LoadingOutlined','#1677FF']},c=kinds[i.type]||kinds.info;
nodes.push({...box(0,0,W,H,'#FFFFFF',8),effect:{type:'shadow',shadowType:'outer',blur:16,offset:{x:0,y:6},color:'#0000001F'}});nodes.push(icon(c[0],12,(H-16)/2,16,c[1]));nodes.push(text(i.content,36,8,W-48,H-16));
""")
write('Notification',['message: string = "Notification Title"','description: string = "This is the content of the notification."','type: enum("info", "success", "warning", "error") = "info"','showProgress: boolean = false','pauseOnHover: boolean = true','placement: enum("topRight", "topLeft", "bottomRight", "bottomLeft", "top", "bottom") = "topRight"','actions: string = ""'],"""
const kinds={info:['InfoCircleOutlined','#1677FF'],success:['CheckCircleOutlined','#52C41A'],warning:['ExclamationCircleOutlined','#FAAD14'],error:['CloseCircleOutlined','#FF4D4F']},c=kinds[i.type]||kinds.info;
nodes.push({...box(0,0,W,H,'#FFFFFF',8),effect:{type:'shadow',shadowType:'outer',blur:24,offset:{x:0,y:6},color:'#0000001F'}});nodes.push(icon(c[0],24,24,24,c[1]));nodes.push(text(i.message,60,20,W-108,28,16,'#000000E0','600'));nodes.push({...text(i.description,60,56,W-84,H-72),textAlignVertical:'top'});nodes.push(icon('CloseOutlined',W-34,20,14,'#00000073'));if(i.showProgress)nodes.push(box(8,H-3,W-16,2,c[1],1));if(i.actions)child(i.actions,W-164,H-48,140,32);
""")
write('Progress',['percent: number = 0','type: enum("line", "circle", "dashboard") = "line"','status: enum("normal", "active", "success", "exception") = "normal"','showInfo: boolean = true','size: enum("small", "default") = "default"','strokeWidth: number = 0','strokeColor: color = #1677FF','trailColor: color = #0000000A','strokeLinecap: enum("round", "butt", "square") = "round"','gapDegree: number = 75','steps: number = 0'],"""
const pct=Math.max(0,Math.min(100,Number(i.percent)||0)),success=i.status==='success'||pct===100,fail=i.status==='exception',color=success?'#52C41A':fail?'#FF4D4F':i.strokeColor||'#1677FF',info=i.showInfo!==false;
if(i.type==='circle'||i.type==='dashboard'){const s=Math.min(W,H),thick=Number(i.strokeWidth)||6,gap=i.type==='dashboard'?(i.gapDegree||75):0,start=90+(i.type==='dashboard'?-gap/2:0),sweep=360-gap;nodes.push({type:'ellipse',name:'Progress rail',x:0,y:0,width:s,height:s,innerRadius:1-thick/50,startAngle:start,sweepAngle:sweep,fill:i.trailColor||'#0000000A'});if(pct>0)nodes.push({type:'ellipse',name:'Progress value',x:0,y:0,width:s,height:s,innerRadius:1-thick/50,startAngle:start,sweepAngle:sweep*pct/100,fill:color});if(info){if(success||fail)nodes.push(icon(success?'CheckOutlined':'CloseOutlined',s*.35,s*.35,s*.3,color));else nodes.push(text(pct+'%',0,0,s,s,Math.max(14,s*.2),'#000000E0','400','center'));}}
else{const barW=Math.max(0,W-(info?48:0)),h=Math.min(H,Number(i.strokeWidth)|| (i.size==='small'?6:8)),y=(H-h)/2,steps=Math.max(0,Math.floor(i.steps||0));if(steps){const gap=2,w=(barW-(steps-1)*gap)/steps;for(let n=0;n<steps;n++)nodes.push(box(n*(w+gap),y,w,h,n<Math.round(pct/100*steps)?color:i.trailColor||'#0000000A'));}else{nodes.push(box(0,y,barW,h,i.trailColor||'#0000000A',i.strokeLinecap==='round'?h/2:0));if(pct>0)nodes.push(box(0,y,barW*pct/100,h,color,i.strokeLinecap==='round'?h/2:0));}if(info){if(success||fail)nodes.push(icon(success?'CheckCircleFilled':'CloseCircleFilled',barW+8,(H-14)/2,14,color));else nodes.push(text(pct+'%',barW+8,0,40,H,i.size==='small'?12:14));}}
""")
write('Skeleton',['active: boolean = false','avatar: boolean = false','rows: number = 3','title: boolean = true','loading: boolean = true','round: boolean = false','children: string = ""'],"""
if(i.loading===false){child(i.children,0,0,W,H);return nodes;}const left=i.avatar?56:0,contentW=W-left,c='#0000000F',r=i.round?100:4;if(i.avatar)nodes.push({type:'ref',name:'Skeleton.Avatar',ref:'q4tGS',x:0,y:0,width:40,height:40,inputs:{size:'large',shape:'circle'}});let y=0;if(i.title!==false){nodes.push(box(left,8,contentW*.38,16,c,r));y=48;}for(let n=0;n<Math.max(0,i.rows??3);n++)nodes.push(box(left,y+n*32,contentW*(n===(i.rows??3)-1?.61:1),16,c,r));
""")
for name,props,body in [
 ('Skeleton.Button',['size: enum("small", "default", "large") = "default"','shape: enum("default", "circle", "round") = "default"','active: boolean = false','block: boolean = false'],"const h=i.size==='small'?24:i.size==='large'?40:32;nodes.push(box(0,0,i.shape==='circle'?h:W,h,'#0000000F',i.shape==='default'?4:h/2));"),
 ('Skeleton.Avatar',['size: enum("small", "default", "large") = "default"','shape: enum("circle", "square") = "circle"','active: boolean = false'],"const s=Math.min(W,H);nodes.push(box(0,0,s,s,'#0000000F',i.shape==='square'?4:s/2));"),
 ('Skeleton.Input',['size: enum("small", "default", "large") = "default"','active: boolean = false','block: boolean = false'],"nodes.push(box(0,0,W,i.size==='small'?24:i.size==='large'?40:32,'#0000000F',4));"),
 ('Skeleton.Image',['active: boolean = false'],"nodes.push(box(0,0,W,H,'#0000000F',4));nodes.push(icon('PictureFilled',(W-40)/2,(H-40)/2,40,'#00000026'));"),
 ('Skeleton.Node',['active: boolean = false','children: string = ""'],"nodes.push(box(0,0,W,H,'#0000000F',4));child(i.children,0,0,W,H);")]:write(name,props,body)
write('Spin',['size: enum("small", "default", "large") = "default"','spinning: boolean = true','tip: string = ""','fullscreen: boolean = false','children: string = ""'],"""
child(i.children,0,0,W,H);if(i.spinning===false)return nodes;if(i.children||i.fullscreen)nodes.push(box(0,0,W,H,i.fullscreen?'#00000073':'#FFFFFFA6'));const s=i.size==='small'?14:i.size==='large'?32:20,x=(W-s)/2,y=(H-s-(i.tip?28:0))/2,r=s*.28;[[0,0,.35],[s-r,0,.6],[s-r,s-r,1],[0,s-r,.8]].forEach(([dx,dy,o])=>nodes.push({type:'ellipse',name:'Spin dot',x:x+dx,y:y+dy,width:r,height:r,fill:'#1677FF',opacity:o}));if(i.tip)nodes.push(text(i.tip,0,y+s+8,W,22,14,'#1677FF','400','center'));
""")
write('Drawer',['title: string = "Basic Drawer"','children: string = "Some contents..."','open: boolean = true','placement: enum("left", "right", "top", "bottom") = "right"','width: number = 378','height: number = 256','mask: boolean = true','closable: boolean = true','loading: boolean = false'],"""
if(!i.open)return nodes;const horizontal=i.placement==='left'||i.placement==='right',dw=horizontal?Math.min(W,i.width||378):W,dh=horizontal?H:Math.min(H,i.height||256),x=i.placement==='right'?W-dw:0,y=i.placement==='bottom'?H-dh:0;if(i.mask)nodes.push(box(0,0,W,H,'#00000073'));nodes.push(box(x,y,dw,dh));if(i.closable)nodes.push(icon('CloseOutlined',x+24,y+22,14,'#00000073'));nodes.push(text(i.title,x+(i.closable?56:24),y+16,dw-80,24,16,'#000000E0','600'));nodes.push(box(x,y+55,dw,1,'#F0F0F0'));if(i.loading)nodes.push({type:'ref',ref:'DAA17',name:'Skeleton',x:x+24,y:y+80,width:dw-48,height:120,inputs:{avatar:false,rows:3,loading:true}});else child(i.children,x+24,y+80,dw-48,dh-104);
""")
write('Modal',['title: string = "Basic Modal"','children: string = "Some contents..."','open: boolean = true','width: number = 520','centered: boolean = false','closable: boolean = true','mask: boolean = true','okText: string = "OK"','cancelText: string = "Cancel"','confirmLoading: boolean = false','loading: boolean = false','footer: boolean = true'],"""
if(!i.open)return nodes;const w=Math.min(W,i.width||520),h=Math.min(H,260),x=(W-w)/2,y=i.centered?(H-h)/2:0;if(i.mask)nodes.push(box(0,0,W,H,'#00000073'));nodes.push({...box(x,y,w,h,'#FFFFFF',8),effect:{type:'shadow',shadowType:'outer',blur:24,offset:{x:0,y:6},color:'#00000026'}});nodes.push(text(i.title,x+24,y+16,w-72,24,16,'#000000E0','600'));if(i.closable)nodes.push(icon('CloseOutlined',x+w-34,y+22,14,'#00000073'));if(i.loading)nodes.push({type:'ref',name:'Skeleton',ref:'DAA17',x:x+24,y:y+64,width:w-48,height:120,inputs:{loading:true,avatar:false,rows:3}});else child(i.children,x+24,y+56,w-48,h-120);if(i.footer!==false){nodes.push(button(i.cancelText||'Cancel',x+w-176,y+h-52,80));const ok=button(i.okText||'OK',x+w-88,y+h-52,64,true);ok.inputs.loading=!!i.confirmLoading;nodes.push(ok);}
""")
write('Popconfirm',['title: string = "Delete the task"','description: string = "Are you sure to delete this task?"','open: boolean = true','showCancel: boolean = true','okText: string = "Yes"','cancelText: string = "No"','placement: enum("top", "bottom", "left", "right") = "top"'],"""
if(!i.open)return nodes;nodes.push({...box(0,0,W,H,'#FFFFFF',8),effect:{type:'shadow',shadowType:'outer',blur:16,offset:{x:0,y:4},color:'#00000026'}});nodes.push(icon('ExclamationCircleFilled',12,16,14,'#FAAD14'));nodes.push(text(i.title,34,12,W-46,22,14,'#000000E0','600'));if(i.description)nodes.push({...text(i.description,34,40,W-46,H-78),textAlignVertical:'top'});if(i.showCancel)nodes.push(button(i.cancelText||'No',W-120,H-36,48,false,'small'));nodes.push(button(i.okText||'Yes',W-64,H-36,52,true,'small'));
""")
# These wrappers must return their actual nested component, not an expression discarded by JavaScript.
for name in ['Affix','App','BackTop']:
 s=(p/(name+'.js')).read_text().replace('\n__output;','\nreturn __output;');(p/(name+'.js')).write_text(s)
write('Result',['status: enum("success", "info", "warning", "error", "403", "404", "500") = "info"','title: string = "Successfully Purchased Cloud Server ECS!"','subTitle: string = "Order number: 2017182818828182881"','extra: string = ""','children: string = ""'],"""
const numeric=['403','404','500'].includes(i.status),kinds={success:['CheckCircleFilled','#52C41A'],info:['InfoCircleFilled','#1677FF'],warning:['WarningFilled','#FAAD14'],error:['CloseCircleFilled','#FF4D4F']},c=kinds[i.status]||kinds.info,top=48,imgH=numeric?295:72;
if(numeric)nodes.push({type:'rectangle',name:'Official result illustration',x:(W-250)/2,y:top,width:250,height:295,fill:{type:'image',url:'images/antd-result-'+i.status+'.svg',mode:'fit'}});else nodes.push(icon(c[0],(W-72)/2,top,72,c[1]));let y=top+imgH+24;nodes.push(text(i.title,24,y,W-48,32,24,'#000000E0','400','center'));y+=40;nodes.push({...text(i.subTitle,32,y,W-64,44,14,'#00000073','400','center'),textAlignVertical:'top'});y+=52;if(i.extra)child(i.extra,24,y,W-48,40);if(i.children)child(i.children,40,y+64,W-80,Math.max(40,H-y-88));
""")
write('Watermark',['content: string = "Ant Design"','children: string = ""','image: string = ""','rotate: number = -22','font: string = "{}"','gap: string = "[100,100]"','offset: string = "[50,50]"','width: number = 120','height: number = 64','zIndex: number = 9','inherit: boolean = true'],"""
child(i.children,0,0,W,H);let font={},gap=[100,100],offset=[50,50];try{font=JSON.parse(i.font||'{}');gap=JSON.parse(i.gap||'[100,100]');offset=JSON.parse(i.offset||'[50,50]')}catch{}const iw=i.width||120,ih=i.height||64,gx=iw+gap[0],gy=ih+gap[1];for(let y=offset[1];y+ih<H;y+=gy)for(let x=offset[0];x+iw<W;x+=gx){if(i.image)nodes.push({type:'rectangle',name:'Watermark image',x,y,width:iw,height:ih,rotation:i.rotate??-22,fill:{type:'image',url:i.image,mode:'fit'},opacity:.15});else nodes.push({...text(i.content,x,y,iw,ih,font.fontSize||16,font.color||'#00000026','400','center'),rotation:i.rotate??-22});}
""")
