Update("t_3001", { content: "1. Standard Variants & Status Matrix" });
Update("sub_3002", { content: "Deconstruct standard variants (Outlined, Filled, Borderless, Underlined) across Normal, Value, Focused, Warning, Error, and Disabled states" });
Update("col_3003", { content: "Outlined (Default)" });
Update("col_3004", { content: "Filled" });
Update("col_3005", { content: "Borderless" });
Update("col_3006", { content: "Underlined" });
Update("row_3007", { content: "Normal" });
Update("inst_3008", { inputs: {"placeholder":"Filled input","variant":"filled"} });
Update("inst_3009", { inputs: {"placeholder":"Borderless input","variant":"borderless"} });
Update("inst_3010", { inputs: {"placeholder":"Underlined input","variant":"underlined"} });
Update("row_3011", { content: "Value" });
Update("inst_3012", { inputs: {"value":99,"variant":"outlined"} });
Update("inst_3013", { inputs: {"value":99,"variant":"filled"} });
Update("inst_3014", { inputs: {"value":99,"variant":"borderless"} });
Update("inst_3015", { inputs: {"value":99,"variant":"underlined"} });
Update("row_3016", { content: "Focused" });
Update("inst_3017", { inputs: {"value":99,"focused":true,"variant":"outlined"} });
Update("inst_3018", { inputs: {"value":99,"focused":true,"variant":"filled"} });
Update("inst_3019", { inputs: {"value":99,"focused":true,"variant":"borderless"} });
Update("inst_3020", { inputs: {"value":99,"focused":true,"variant":"underlined"} });
Update("row_3021", { content: "Warning" });
Update("inst_3022", { inputs: {"value":99,"status":"warning","variant":"outlined"} });
Update("inst_3023", { inputs: {"value":99,"status":"warning","variant":"filled"} });
Update("inst_3024", { inputs: {"value":99,"status":"warning","variant":"borderless"} });
Update("inst_3025", { inputs: {"value":99,"status":"warning","variant":"underlined"} });
Update("row_3026", { content: "Error" });
Update("inst_3027", { inputs: {"value":99,"status":"error","variant":"outlined"} });
Update("inst_3028", { inputs: {"value":99,"status":"error","variant":"filled"} });
Update("inst_3029", { inputs: {"value":99,"status":"error","variant":"borderless"} });
Update("inst_3030", { inputs: {"value":99,"status":"error","variant":"underlined"} });
Update("row_3031", { content: "Disabled" });
Update("inst_3032", { inputs: {"value":99,"disabled":true,"variant":"outlined"} });
Update("inst_3033", { inputs: {"value":99,"disabled":true,"variant":"filled"} });
Update("inst_3034", { inputs: {"value":99,"disabled":true,"variant":"borderless"} });
Update("inst_3035", { inputs: {"value":99,"disabled":true,"variant":"underlined"} });
Update("t_3036", { content: "2. Size & Mode Matrix (Large, Middle, Small)" });
Update("sub_3037", { content: "Visual presentation of Large (40px), Middle (32px), and Small (24px) across standard, currency prefix, spinner, and suffix configurations" });
Update("col_3038", { content: "Standard Input" });
Update("col_3039", { content: "Prefix Currency (¥)" });
Update("col_3040", { content: "Digit Spinner Mode" });
Update("col_3041", { content: "Suffix Unit (RMB)" });
Update("row_3042", { content: "Large (40px)" });
Update("inst_3043", { inputs: {"size":"large","value":100} });
Update("inst_3044", { inputs: {"size":"large","prefix":"￥","value":100} });
Update("inst_3045", { inputs: {"size":"large","mode":"spinner","value":3} });
Update("inst_3046", { inputs: {"size":"large","suffix":"RMB","value":100} });
Update("row_3047", { content: "Middle (32px)" });
Update("inst_3048", { inputs: {"size":"middle","value":100} });
Update("inst_3049", { inputs: {"size":"middle","prefix":"￥","value":100} });
Update("inst_3050", { inputs: {"size":"middle","mode":"spinner","value":3} });
Update("inst_3051", { inputs: {"size":"middle","suffix":"RMB","value":100} });
Update("row_3052", { content: "Small (24px)" });
Update("inst_3053", { inputs: {"size":"small","value":100} });
Update("inst_3054", { inputs: {"size":"small","prefix":"￥","value":100} });
Update("inst_3055", { inputs: {"size":"small","mode":"spinner","value":3} });
Update("inst_3056", { inputs: {"size":"small","suffix":"RMB","value":100} });
Update("t_3057", { content: "3. Prefix, Suffix & Addons" });
Update("sub_3058", { content: "Comprehensive showcase of currency prefix, unit suffix, protocol addons, and prefix icons" });
Update("lbl_3059", { content: "Prefix Icons & Currency" });
Update("inst_3060", { inputs: {"prefixIcon":"ClockCircleOutlined","value":60,"suffix":"min"} });
Update("inst_3061", { inputs: {"prefix":"￥","value":"998.00"} });
Update("inst_3062", { inputs: {"prefix":"$","value":1250,"formatter":true} });
Update("lbl_3063", { content: "Addon Before & After Slots" });
Update("inst_3064", { inputs: {"addonBefore":"+86","value":18888888888} });
Update("inst_3065", { inputs: {"addonBefore":"https://","addonAfter":".com","value":1000} });
Update("inst_3066", { inputs: {"addonAfter":"USD","value":50} });
Update("lbl_3067", { content: "Suffix & Units" });
Update("inst_3068", { inputs: {"suffix":"RMB","value":100} });
Update("inst_3069", { inputs: {"suffix":"%","value":100,"formatter":true} });
Update("inst_3070", { inputs: {"prefix":"$","suffix":"USD","value":88} });
Update("t_3071", { content: "4. Advanced Modes, Precision & Validation" });
Update("sub_3072", { content: "Showcase step spinner, high precision decimals (stringMode), thousandths/percentage formatters, and out-of-range validation" });
Update("lbl_3073", { content: "Step Spinner Mode" });
Update("inst_3074", { inputs: {"mode":"spinner","variant":"outlined","value":3,"min":1,"max":10} });
Update("inst_3075", { inputs: {"mode":"spinner","variant":"filled","value":5,"min":1,"max":10} });
Update("inst_3076", { inputs: {"mode":"spinner","disabled":true,"value":3} });
Update("lbl_3077", { content: "High Precision & Decimals" });
Update("inst_3078", { inputs: {"value":"1.00000000000001","step":"0.00000000000001","stringMode":true} });
Update("inst_3079", { inputs: {"value":"99.90","precision":2} });
Update("inst_3080", { inputs: {"value":"100.000","precision":3} });
Update("lbl_3081", { content: "Number Formatter" });
Update("inst_3082", { inputs: {"value":1000,"prefix":"$","formatter":true} });
Update("inst_3083", { inputs: {"value":100,"suffix":"%","formatter":true} });
Update("inst_3084", { inputs: {"value":1000000,"prefix":"¥","formatter":true} });
Update("lbl_3085", { content: "Out of Range Validation" });
Update("inst_3086", { inputs: {"min":1,"max":10,"value":99} });
Update("inst_3087", { inputs: {"min":0,"max":100,"value":-5} });
Update("inst_3088", { inputs: {"status":"warning","value":99} });