import {createRequire} from 'node:module';
import {loadTypographyFonts} from './typography-fonts.mjs';
const require=createRequire(import.meta.url),ar=createRequire(require.resolve('antd'));
export async function setup(page){await page.setContent('<!doctype html><div id="root"></div>');await page.addStyleTag({path:require.resolve('antd/dist/reset.css')});for(const path of [require.resolve('react/package.json').replace('package.json','umd/react.development.js'),require.resolve('react-dom/package.json').replace('package.json','umd/react-dom.development.js'),ar.resolve('dayjs/dayjs.min.js'),require.resolve('antd/dist/antd.min.js')])await page.addScriptTag({path});await loadTypographyFonts(page);}
export async function sample(page,props,state='normal'){
 await page.evaluate(props=>{const icon=props.icon?React.createElement('svg',{viewBox:'0 0 24 24',width:'1em',height:'1em'},React.createElement('path',{d:'M0 0h24v24H0z'})):undefined;ReactDOM.render(React.createElement(antd.ConfigProvider,{theme:{token:{fontFamily:'Inter'}}},React.createElement(antd.FloatButton,{...props,icon,style:{position:'relative',inset:'auto',margin:40}})),document.getElementById('root'));},props);
 await page.mouse.move(0,0);if(state==='focus'){await page.evaluate(()=>document.activeElement.blur());await page.keyboard.press('Tab');}else if(state!=='normal')await page.locator('button.ant-float-btn').hover();if(state==='active')await page.mouse.down();await page.waitForTimeout(220);
 const result=await page.evaluate(()=>{const el=document.querySelector('button.ant-float-btn'),c=getComputedStyle(el),b=el.getBoundingClientRect();const rect=n=>{if(!n)return null;const r=n.getBoundingClientRect(),s=getComputedStyle(n);return{x:r.x-b.x,y:r.y-b.y,width:r.width,height:r.height,fontSize:s.fontSize,lineHeight:s.lineHeight,color:s.color};};return{width:b.width,height:b.height,bg:c.backgroundColor,color:c.color,border:c.borderColor,borderWidth:parseFloat(c.borderWidth),radius:parseFloat(c.borderRadius),shadow:c.boxShadow,outlineWidth:parseFloat(c.outlineWidth),outlineColor:c.outlineColor,icon:rect(el.querySelector('.ant-float-btn-icon')),text:rect(el.querySelector('.ant-float-btn-content')),badge:rect(el.querySelector('.ant-badge-count,.ant-badge-dot'))};});if(state==='active')await page.mouse.up();return result;
}
