{
  const c = Get('v4Pii3');
  Update('v4Pii3', { layout: 'vertical' });
  Replace(c.children[0].id, {"type":"frame","id":"iJQJr","name":"section","context":"section","width":"fill_container","fill":"#ffffff","cornerRadius":[8,8,0,0],"stroke":"#0505050f","strokeWidth":{"bottom":1},"strokeAlignment":"inner","layout":"vertical","padding":[42,24,51,24],"children":[{"type":"frame","id":"ghost_bg_wrap","name":"Ghost Wrapper","fill":"#bec8c8","cornerRadius":6,"padding":16,"layout":"horizontal","gap":8,"alignItems":"center","children":[{"type":"ref","ref":"antd-button-live-origin","id":"btn_jdysyf","name":"Btn · Primary Ghost","width":79,"height":32,"inputs":{"children":"Primary","type":"primary","ghost":true}},{"type":"ref","ref":"antd-button-live-origin","id":"btn_ufamj6","name":"Btn · Default Ghost","width":77,"height":32,"inputs":{"children":"Default","type":"default","ghost":true}},{"type":"ref","ref":"antd-button-live-origin","id":"btn_rsl8td","name":"Btn · Dashed Ghost","width":79,"height":32,"inputs":{"children":"Dashed","type":"dashed","ghost":true}},{"type":"ref","ref":"antd-button-live-origin","id":"btn_x1n2jo","name":"Btn · Danger Ghost","width":77,"height":32,"inputs":{"children":"Danger","type":"primary","danger":true,"ghost":true}}]}]});
}
{
  const c = Get('S9apJ');
  Update('S9apJ', { layout: 'vertical' });
  Replace(c.children[0].id, {"type":"frame","id":"EoDJP","name":"section","context":"section","width":"fill_container","fill":"#ffffff","cornerRadius":[8,8,0,0],"stroke":"#0505050f","strokeWidth":{"bottom":1},"strokeAlignment":"inner","layout":"vertical","padding":[42,24,51,24],"children":[{"type":"ref","ref":"antd-button-live-origin","id":"btn_dq065u","name":"Btn · Primary Block","width":"fill_container","height":32,"inputs":{"children":"Primary","type":"primary","block":true}},{"type":"ref","ref":"antd-button-live-origin","id":"btn_bagbp1","name":"Btn · Default Block","width":"fill_container","height":32,"inputs":{"children":"Default","type":"default","block":true}},{"type":"ref","ref":"antd-button-live-origin","id":"btn_uf8xqk","name":"Btn · Dashed Block","width":"fill_container","height":32,"inputs":{"children":"Dashed","type":"dashed","block":true}},{"type":"ref","ref":"antd-button-live-origin","id":"btn_yq4fft","name":"Btn · Disabled Block","width":"fill_container","height":32,"inputs":{"children":"disabled","type":"default","disabled":true,"block":true}},{"type":"ref","ref":"antd-button-live-origin","id":"btn_7zxmaq","name":"Btn · Text Block","width":"fill_container","height":32,"inputs":{"children":"text","type":"text","block":true}},{"type":"ref","ref":"antd-button-live-origin","id":"btn_s662fz","name":"Btn · Link Block","width":"fill_container","height":32,"inputs":{"children":"Link","type":"link","block":true}}],"gap":8});
}
{
  const c = Get('RbSSB');
  Update('RbSSB', { layout: 'vertical' });
  Replace(c.children[0].id, {"type":"frame","id":"O4ylNl","name":"section","context":"section","width":"fill_container","fill":"#ffffff","cornerRadius":[8,8,0,0],"stroke":"#0505050f","strokeWidth":{"bottom":1},"strokeAlignment":"inner","layout":"horizontal","padding":[42,24,51,24],"children":[{"type":"ref","ref":"antd-button-live-origin","id":"btn_24kjxb","name":"Btn · Disabled Wave","width":86,"height":32,"inputs":{"children":"Disabled","type":"primary","disabled":true}},{"type":"ref","ref":"antd-button-live-origin","id":"btn_wf5xwk","name":"Btn · Default Wave","width":77,"height":32,"inputs":{"children":"Default","type":"primary"}},{"type":"ref","ref":"antd-button-live-origin","id":"btn_ibqmue","name":"Btn · Inset Wave","width":62,"height":32,"inputs":{"children":"Inset","type":"primary"}},{"type":"ref","ref":"antd-button-live-origin","id":"btn_3jgv80","name":"Btn · Shake Wave","width":70,"height":32,"inputs":{"children":"Shake","type":"primary"}},{"type":"ref","ref":"antd-button-live-origin","id":"btn_0q9riw","name":"Btn · Happy Work Wave","width":110,"height":32,"inputs":{"children":"Happy Work","type":"primary"}}],"gap":16,"alignItems":"center"});
}
{
  const c = Get('XK6gC');
  Update('XK6gC', { layout: 'vertical' });
  Replace(c.children[0].id, {"type":"frame","id":"olIwy","name":"section","context":"section","width":"fill_container","fill":"#ffffff","cornerRadius":[8,8,0,0],"stroke":"#0505050f","strokeWidth":{"bottom":1},"strokeAlignment":"inner","layout":"horizontal","padding":[42,24,51,24],"children":[{"type":"ref","ref":"antd-button-live-origin","id":"btn_2s5vf9","name":"Btn · Object Styling","width":73,"height":32,"inputs":{"children":"Object","type":"default"}},{"type":"ref","ref":"antd-button-live-origin","id":"btn_ahxc3i","name":"Btn · Function Styling","width":86,"height":32,"inputs":{"children":"Function","type":"primary","color":"default"}}],"gap":8,"alignItems":"center"});
}