import fs from 'node:fs';import assert from 'node:assert/strict';import {chromium} from '@playwright/test';import {setup} from '../floatbutton-browser.mjs';import {renderNavigation} from './render.mjs';
const metrics=JSON.parse(fs.readFileSync(new URL('../fonts/divider-metrics.json',import.meta.url),'utf8'))['400'];
const render=(n,p,w=740,h=240)=>renderNavigation(n,p,w,h,metrics);
const jobs=JSON.parse(fs.readFileSync('registry/navigation-instance-migration.json','utf8')).instances;
let snapshots=0;
for(const j of jobs){for(const width of [400,740,1614]){const out=render(j.component,j.props,width,240);for(const n of out){assert(n.type!=='ref');for(const k of ['x','y','width','height'])assert(Number.isFinite(n[k]),`${j.component} ${k}`);assert(n.width>=0&&n.height>=0);if(n.type==='script')assert(fs.existsSync(new URL('../../canvas-components/'+n.scriptUri.split('/').at(-1),import.meta.url)));}snapshots++;}}
const items=[{title:'Finished',content:'This is a content.'},{title:'In Progress',content:'This is a content.',subTitle:'Left 00:00:08'},{title:'Waiting',content:'This is a content.'}];
assert.notDeepEqual(render('Steps',{items,current:0}),render('Steps',{items,current:2}));
assert(render('Dropdown',{open:true,menu:{items:[{key:'1',label:'Menu item'}]}}).some(n=>n.scriptUri?.endsWith('/Menu.js')&&n.inputs.dropdownMenu));
const basicMenuItems=[{key:'1',label:'1st menu item'},{key:'2',disabled:true,label:'2nd menu item (disabled)',icon:'SmileOutlined'},{key:'3',disabled:true,label:'3rd menu item (disabled)'},{key:'4',danger:true,label:'a danger item'}];
const openDropdown=render('Dropdown',{open:true,arrow:true,triggerWidth:64,triggerHeight:22,popupWidth:200,popupHeight:136,menu:{items:basicMenuItems}},740,184),openPopup=openDropdown.find(n=>n.name==='Dropdown popup'),openMenu=openDropdown.find(n=>n.scriptUri?.endsWith('/Menu.js')),openRows=render('Menu',openMenu.inputs,openMenu.width,openMenu.height);
assert(openPopup.width>220&&openPopup.width<224,'Dropdown popup must expand to the official longest-item width');
const disabledWithIcon=openRows.find(n=>n.name==='Content'&&n.content==='2nd menu item (disabled)');assert(disabledWithIcon.width>=Math.ceil(14*'2nd menu item (disabled)'.split('').reduce((w,c)=>w+(metrics.widths[c]??.6),0))-2,'Dropdown labels must stay on one line');
const officialHorizontalItems=[{key:'mail',label:'Navigation One',icon:'MailOutlined'},{key:'app',disabled:true,label:'Navigation Two',icon:'AppstoreOutlined'},{key:'SubMenu',label:'Navigation Three - Submenu',icon:'SettingOutlined',children:[{key:'1',label:'Option 1'}]},{key:'alipay',label:'Navigation Four - Link'}];
const horizontalMenu=render('Menu',{items:officialHorizontalItems,selectedKeys:['mail'],openKeys:[],mode:'horizontal'},740,46),horizontalLabels=horizontalMenu.filter(n=>n.name==='Content');
assert.deepEqual(horizontalLabels.map(n=>[n.content,n.y,n.height]),officialHorizontalItems.map(n=>[n.label,12,22]));
assert.equal(horizontalLabels[0].x,40);assert(Math.abs(horizontalLabels[0].width-101.623046875)<.01);assert(!horizontalMenu.some(n=>n.inputs?.name==='DownOutlined'),'Horizontal Menu must not draw the inline submenu arrow');
const officialInlineItems=[{key:'sub1',label:'Navigation One',icon:'MailOutlined',children:[{key:'g1',type:'group',label:'Item 1',children:[{key:'1',label:'Option 1'},{key:'2',label:'Option 2'}]},{key:'g2',type:'group',label:'Item 2',children:[{key:'3',label:'Option 3'},{key:'4',label:'Option 4'}]}]},{key:'sub2',label:'Navigation Two',icon:'AppstoreOutlined',children:[]},{type:'divider'},{key:'sub4',label:'Navigation Three',icon:'SettingOutlined',children:[]},{key:'grp',type:'group',label:'Group',children:[{key:'13',label:'Option 13'},{key:'14',label:'Option 14'}]}];
const inlineMenu=render('Menu',{items:officialInlineItems,selectedKeys:['1'],openKeys:['sub1'],mode:'inline'},256,535),inlineSurface=inlineMenu.find(n=>n.name==='Inline submenu surface'),inlineSelection=inlineMenu.find(n=>n.name==='Selected menu item');
assert.deepEqual([inlineSurface.x,inlineSurface.y,inlineSurface.width,inlineSurface.height],[0,48,255,260]);assert.deepEqual([inlineSelection.x,inlineSelection.y,inlineSelection.width,inlineSelection.height],[4,90,247,40]);assert.equal(inlineMenu.find(n=>n.name==='Content'&&n.content==='Navigation One').fill,'#1677ff');
const compactButton={type:'script',name:'Button',scriptUri:'../canvas-components/Button.js',inputs:{children:'',icon:JSON.stringify({type:'script',name:'Icon',scriptUri:'../canvas-components/Icon.js',inputs:{name:'EllipsisOutlined'},width:14,height:14})}};
const compactDropdownTrigger=render('Dropdown',{children:JSON.stringify(compactButton),triggerWidth:32,triggerHeight:32,compactPlacement:'end',compactOrientation:'horizontal'},32,32)[0];
assert.equal(compactDropdownTrigger.scriptUri,'../canvas-components/Button.js');
assert.equal(compactDropdownTrigger.inputs.compactPlacement,'end');
assert.equal(compactDropdownTrigger.inputs.compactOrientation,'horizontal');
assert(render('Pagination',{showSizeChanger:true}).some(n=>n.scriptUri?.endsWith('/Select.js')));
const paginationComposite=render('Pagination',{total:500,current:2,showSizeChanger:true,showQuickJumper:true},740,32),paginationSelect=paginationComposite.find(n=>n.scriptUri?.endsWith('/Select.js')),paginationInput=paginationComposite.find(n=>n.scriptUri?.endsWith('/Input.js'));
assert(Math.abs(paginationSelect.width-102.7646484375)<.01);assert.deepEqual([paginationInput.x,paginationInput.width,paginationInput.inputs.placeholder,paginationInput.inputs.allowClear],[522.3798828125,50,'',false]);
const paginationSimple=render('Pagination',{total:50,current:2,simple:true},740,32),simpleInput=paginationSimple.find(n=>n.scriptUri?.endsWith('/Input.js')),simpleRight=paginationSimple.filter(n=>n.inputs?.name==='RightOutlined').at(-1);
assert.deepEqual([simpleInput.x,simpleInput.width,simpleInput.inputs.value,simpleInput.inputs.textAlign],[40,50,'2','center']);assert(Math.abs((simpleRight.x-10)-135.3505859375)<.01);
const inputSource=fs.readFileSync('canvas-components/Input.js','utf8'),blankQuickInput=new Function('pencil',inputSource)({input:paginationInput.inputs,width:paginationInput.width,height:paginationInput.height});assert.equal(blankQuickInput[0].width,50);assert.equal(blankQuickInput.find(n=>n.type==='text').content,'');
const tabItems=[1,2,3].map(k=>({key:String(k),label:'Tab '+k,children:'Content of Tab Pane '+k}));
const tabsLine=render('Tabs',{items:tabItems,activeKey:'1',type:'line',size:'middle'},740,84),tabsCardSmall=render('Tabs',{items:tabItems,activeKey:'1',type:'card',size:'small'},740,70),tabsVertical=render('Tabs',{items:tabItems,activeKey:'1',type:'line',tabPlacement:'start'},740,146),tabsBottom=render('Tabs',{items:tabItems,activeKey:'1',type:'line',tabPlacement:'bottom'},740,84);
assert.deepEqual(tabsLine.filter(n=>n.name==='Content').slice(0,3).map(n=>[n.x,n.y,n.width,n.height]),[[0,12,34.0771484375,22],[66.0771484375,12,36.9208984375,22],[134.998046875,12,37.0302734375,22]]);
assert.deepEqual(tabsCardSmall.filter(n=>/^Tab \d$/.test(n.name)).map(n=>[n.x,n.width,n.height,n.cornerRadius,n.fill]),[[0,52.0771484375,32,[6,6,0,0],'#fff'],[54.0771484375,54.9208984375,32,[6,6,0,0],'#00000005'],[110.998046875,55.0302734375,32,[6,6,0,0],'#00000005']]);
assert(Math.abs(tabsVertical.find(n=>n.name==='Tab bar divider').x-84.0302734375)<.01);assert.deepEqual(tabsVertical.filter(n=>n.name==='Content').slice(0,3).map(n=>[n.x,n.y]),[[24,8],[24,62],[24,116]]);assert.equal(tabsBottom.find(n=>n.name==='Active tab indicator').y,38);
const tabsExtra=render('Tabs',{items:tabItems,activeKey:'1',extraStart:JSON.stringify({type:'script',name:'Extra',scriptUri:'../canvas-components/Button.js',inputs:{children:'Left Extra Action'}}),extraEnd:JSON.stringify({type:'script',name:'Extra',scriptUri:'../canvas-components/Button.js',inputs:{children:'Right Extra Action'}}),extraStartMargin:16,extraEndMargin:16},740,84),extraButtons=tabsExtra.filter(n=>n.name==='Extra');
assert(Math.abs(extraButtons[0].width-141.5732421875)<.01);assert(Math.abs(extraButtons[1].width-150.056640625)<.01);assert(Math.abs(tabsExtra.find(n=>n.name==='Content').x-extraButtons[0].width-16)<.01);assert.equal(extraButtons[1].x+extraButtons[1].width,740);
const breadcrumbStyles={root:{border:'1px solid #f0f0f0',padding:8,borderRadius:4},item:{color:'#1890ff'},separator:{color:'#00000073'}};
const styledBreadcrumb=render('Breadcrumb',{items:[{title:'Ant Design'},{title:'Component'}],styles:breadcrumbStyles},774,40);
assert.deepEqual(styledBreadcrumb.find(n=>n.name==='Breadcrumb root'),{type:'rectangle',name:'Breadcrumb root',x:0,y:0,width:774,height:40,fill:'#00000000',cornerRadius:4,stroke:'#f0f0f0',strokeWidth:1,strokeAlignment:'inner'});
assert(styledBreadcrumb.filter(n=>n.name==='Content').every(n=>n.y===9));
assert.equal(styledBreadcrumb.find(n=>n.name==='Content').fill,'#1890ff');
const linkedStyledBreadcrumb=render('Breadcrumb',{items:[{title:'Ant Design'},{title:'Component',href:''}],styles:breadcrumbStyles},774,40).filter(n=>n.name==='Content');
assert.deepEqual(linkedStyledBreadcrumb.map(n=>n.fill),['#1890ff','#00000073','#00000073']);

const instances=JSON.parse(fs.readFileSync('registry/navigation-instance-snapshots.json','utf8'));
assert.equal(instances.filter(n=>n.reusable).length,7);
for(const n of instances){
 const src=fs.readFileSync(new URL('../../canvas-components/'+n.scriptUri.split('/').at(-1),import.meta.url),'utf8');const defaults={};for(const m of src.matchAll(/@input (\w+): .*? = (.+)/g)){try{defaults[m[1]]=JSON.parse(m[2])}catch{defaults[m[1]]=m[2]}}
 const output=new Function('pencil',src)({input:{...defaults,...n.inputs},width:n.bounds.width,height:n.bounds.height});
 const inspect=nodes=>{for(const node of nodes){assert(node.type!=='ref',n.name);assert(!node.ref,n.name);if(node.type==='script')assert(node.scriptUri);if(node.children)inspect(node.children);}};inspect(output);
}
const compactGroups=instances.filter(n=>n.name==='Space.Compact · Dropdown group');
assert.equal(compactGroups.length,9,'Every official Dropdown split/loading pair must use Space.Compact');
const compactSource=fs.readFileSync('canvas-components/Space.Compact.js','utf8'),dropdownSource=fs.readFileSync('canvas-components/Dropdown.js','utf8'),buttonSource=fs.readFileSync('canvas-components/Button.js','utf8');
for(const group of compactGroups){
 const pair=new Function('pencil',compactSource)({input:group.inputs,width:group.bounds.width,height:group.bounds.height});
 assert.equal(pair.length,2);assert.equal(pair[0].inputs.compactPlacement,'start');assert.equal(pair[1].inputs.compactPlacement,'end');assert.equal(pair[1].x,pair[0].width-1);
 const endTrigger=new Function('pencil',dropdownSource)({input:pair[1].inputs,width:pair[1].width,height:pair[1].height})[0];
 assert.equal(endTrigger.inputs.compactPlacement,'end');
 const startSurface=new Function('pencil',buttonSource)({input:pair[0].inputs,width:pair[0].width,height:pair[0].height})[0],endSurface=new Function('pencil',buttonSource)({input:endTrigger.inputs,width:endTrigger.width,height:endTrigger.height})[0];
 const radius=group.inputs.size==='small'?4:6;assert.deepEqual(startSurface.cornerRadius,[radius,0,0,radius]);assert.deepEqual(endSurface.cornerRadius,[0,radius,radius,0]);
}
const compactChildren=n=>JSON.parse(n.inputs.children);
const compactDescriptor=label=>compactGroups.map(compactChildren).find(([a])=>a.inputs.children===label);
for(const [label,iconName,danger] of [['With Tooltip','LoadingOutlined',false],['Danger','EllipsisOutlined',true]]){const pair=compactDescriptor(label),button=JSON.parse(pair[1].inputs.children),icon=JSON.parse(button.inputs.icon);assert.equal(icon.inputs.name,iconName);assert.equal(button.inputs.danger,danger);}
const loadingPairs=compactGroups.map(compactChildren).filter(([a])=>a.inputs.children==='Submit');
const idlePrimary=loadingPairs.find(([a])=>a.inputs.type==='primary'&&!a.inputs.loading),idleDefault=loadingPairs.find(([a])=>a.inputs.type==='default');
assert.equal(JSON.parse(JSON.parse(idlePrimary[1].inputs.children).inputs.icon).inputs.name,'EllipsisOutlined');assert.equal(JSON.parse(idlePrimary[1].inputs.children).inputs.type,'primary');
assert.equal(JSON.parse(JSON.parse(idleDefault[1].inputs.children).inputs.icon).inputs.name,'DownOutlined');assert.equal(JSON.parse(idleDefault[1].inputs.children).inputs.type,'default');
const parseChildren=n=>{try{return JSON.parse(n.inputs.children||'null')}catch{return null}};
const dropdownLinks=instances.filter(n=>n.scriptUri.endsWith('/Dropdown.js')).map(n=>[n,parseChildren(n)]).filter(([,t])=>t?.name==='Dropdown link');
assert(dropdownLinks.every(([,t])=>(t.children||[]).filter(n=>n.scriptUri?.endsWith('/Icon.js')).every(n=>n.inputs.color==='#1677FF')));const clickLink=dropdownLinks.find(([n])=>n.name==='Dropdown · Trigger mode');assert.equal(clickLink[0].inputs.trigger,'click');assert.equal(clickLink[1].children.filter(n=>n.scriptUri?.endsWith('/Icon.js')).length,1,'Dropdown link must render exactly one arrow icon');
const styledDropdowns=instances.filter(n=>n.name==='Dropdown · Custom semantic dom styling');
assert.equal(styledDropdowns.find(n=>JSON.parse(n.inputs.children).inputs.children==='Function Style').inputs.trigger,'click');
const findNested=(nodes,predicate)=>{const stack=[...nodes];while(stack.length){const node=stack.shift();if(predicate(node))return node;if(node.children)stack.unshift(...node.children)}};
for(const n of styledDropdowns){const trigger=new Function('pencil',dropdownSource)({input:n.inputs,width:n.bounds.width,height:n.bounds.height})[0],surface=new Function('pencil',buttonSource)({input:trigger.inputs,width:trigger.width,height:trigger.height}),label=findNested(surface,x=>x.name==='children'),glyph=findNested(surface,x=>String(x.name).toLowerCase()==='icon');assert(glyph.x>=label.x+label.width+7&&glyph.x+glyph.width<=n.bounds.width-14,`${n.name} icon must preserve the official 8px content gap and button padding`);}

const browser=await chromium.launch({channel:'chrome'});let checks=0;
try{const page=await browser.newPage();await setup(page);await page.addStyleTag({content:'*{transition:none!important;animation:none!important}'});
const paginationControlsActual=await page.evaluate(async()=>{const read=props=>new Promise(resolve=>{ReactDOM.render(React.createElement(antd.ConfigProvider,{theme:{token:{fontFamily:'Inter'}}},React.createElement(antd.Pagination,{...props,style:{width:740}})),document.getElementById('root'));requestAnimationFrame(()=>requestAnimationFrame(()=>{const root=document.querySelector('.ant-pagination').getBoundingClientRect(),box=s=>{const n=document.querySelector(s);if(!n)return null;const b=n.getBoundingClientRect();return{x:b.x-root.x,y:b.y-root.y,w:b.width,h:b.height}};resolve({select:box('.ant-pagination-options-size-changer'),quickInput:box('.ant-pagination-options-quick-jumper input'),simpleInput:box('.ant-pagination-simple-pager input'),next:box('.ant-pagination-next')});}))});return{quick:await read({total:500,current:2,showSizeChanger:true,showQuickJumper:true}),simple:await read({total:50,current:2,simple:true})};});
assert(Math.abs(paginationControlsActual.quick.select.x-paginationSelect.x)<.02);assert(Math.abs(paginationControlsActual.quick.select.w-paginationSelect.width)<.02);assert(Math.abs(paginationControlsActual.quick.quickInput.x-paginationInput.x)<.02);assert.equal(paginationControlsActual.quick.quickInput.w,paginationInput.width);assert.equal(paginationControlsActual.simple.simpleInput.x,simpleInput.x);assert.equal(paginationControlsActual.simple.simpleInput.w,simpleInput.width);assert(Math.abs(paginationControlsActual.simple.next.x-(simpleRight.x-10))<.02);checks++;
const menuActual=await page.evaluate(async()=>{const icon=()=>React.createElement('svg',{viewBox:'0 0 24 24',width:'1em',height:'1em'},React.createElement('path',{d:'M0 0h24v24H0z'}));const items=[{key:'mail',label:'Navigation One',icon:icon()},{key:'app',disabled:true,label:'Navigation Two',icon:icon()},{key:'SubMenu',label:'Navigation Three - Submenu',icon:icon(),children:[{key:'1',label:'Option 1'}]},{key:'alipay',label:'Navigation Four - Link'}];ReactDOM.render(React.createElement(antd.ConfigProvider,{theme:{token:{fontFamily:'Inter'}}},React.createElement(antd.Menu,{items,selectedKeys:['mail'],mode:'horizontal',style:{width:740}})),document.getElementById('root'));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const root=document.querySelector('.ant-menu-root').getBoundingClientRect();return [...document.querySelectorAll('.ant-menu-root > .ant-menu-overflow-item:not(.ant-menu-overflow-item-rest)')].map(n=>{const r=n.getBoundingClientRect(),t=n.querySelector('.ant-menu-title-content').getBoundingClientRect();return{x:r.x-root.x,w:r.width,tx:t.x-root.x,tw:t.width,h:r.height}});});
let menuX=0;horizontalLabels.forEach((n,k)=>{assert(Math.abs(menuActual[k].x-menuX)<.02);assert(Math.abs(menuActual[k].tx-n.x)<.02);assert(Math.abs(menuActual[k].tw-n.width)<.02);assert.equal(menuActual[k].h,46);menuX+=menuActual[k].w;});checks++;
for(const spec of [{type:'line',size:'small',h:76},{type:'line',size:'middle',h:84},{type:'line',size:'large',h:94},{type:'card',size:'small',h:70},{type:'card',size:'middle',h:78},{type:'card',size:'large',h:86},{type:'line',size:'middle',tabPlacement:'start',h:146},{type:'line',size:'middle',tabPlacement:'bottom',h:84}]){
 const actual=await page.evaluate(async ({spec,items})=>{const tabPosition=spec.tabPlacement==='start'?'left':spec.tabPlacement==='end'?'right':spec.tabPlacement;ReactDOM.render(React.createElement(antd.ConfigProvider,{theme:{token:{fontFamily:'Inter'}}},React.createElement(antd.Tabs,{items,type:spec.type,size:spec.size,tabPosition,style:{width:740}})),document.getElementById('root'));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const root=document.querySelector('.ant-tabs').getBoundingClientRect();return{root:{w:root.width,h:root.height},tabs:[...document.querySelectorAll('.ant-tabs-tab')].map(n=>{const b=n.getBoundingClientRect(),t=n.querySelector('.ant-tabs-tab-btn').getBoundingClientRect();return{x:b.x-root.x,y:b.y-root.y,w:b.width,h:b.height,bx:t.x-root.x,by:t.y-root.y,bw:t.width,bh:t.height}}),ink:(()=>{const b=document.querySelector('.ant-tabs-ink-bar').getBoundingClientRect();return{x:b.x-root.x,y:b.y-root.y,w:b.width,h:b.height}})()};},{spec,items:tabItems});
 const expected=render('Tabs',{items:tabItems,activeKey:'1',type:spec.type,size:spec.size,tabPlacement:spec.tabPlacement||'top'},740,spec.h),labels=expected.filter(n=>n.name==='Content').slice(0,3),surfaces=expected.filter(n=>/^Tab \d$/.test(n.name));assert.equal(actual.root.h,spec.h);actual.tabs.forEach((n,k)=>{if(surfaces[k]){const e=surfaces[k];assert(Math.abs(n.x-e.x)<.02);assert(Math.abs(n.y-e.y)<.02);assert(Math.abs(n.w-e.width)<.02);assert.equal(n.h,e.height);}else{const e=labels[k];assert(Math.abs(n.bx-e.x)<.02,`Tabs ${spec.type}/${spec.size}/${spec.tabPlacement||'top'} label x ${k}`);assert(Math.abs(n.by-e.y)<.02);assert(Math.abs(n.bw-e.width)<.02);assert.equal(n.bh,e.height);}});checks++;
}
for(const size of ['middle','small','large']){
 const actual=await page.evaluate(async size=>{ReactDOM.render(React.createElement(antd.ConfigProvider,{theme:{token:{fontFamily:'Inter'}}},React.createElement(antd.Pagination,{total:50,current:2,size})),document.getElementById('root'));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const p=document.querySelector('.ant-pagination').getBoundingClientRect();return [...document.querySelectorAll('.ant-pagination-item')].map(n=>{const b=n.getBoundingClientRect();return{x:b.x-p.x,w:b.width,h:b.height}})},size);
 const expected=render('Pagination',{total:50,current:2,size}).filter(n=>/^Page \d+$/.test(n.name));expected.forEach((n,k)=>{assert(Math.abs(n.x-actual[k].x)<1,`Pagination ${size} x ${k}: ${n.x}/${actual[k].x}`);assert.equal(n.width,actual[k].w);assert.equal(n.height,actual[k].h);});checks++;
}
for(const direction of ['vertical','horizontal']){
 const links=[1,2,3].map(k=>({key:String(k),href:'#'+k,title:'Part '+k}));const actual=await page.evaluate(async ({direction,links})=>{ReactDOM.render(React.createElement(antd.ConfigProvider,{theme:{token:{fontFamily:'Inter'}}},React.createElement(antd.Anchor,{direction,items:links,affix:false,style:{width:740}})),document.getElementById('root'));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const p=document.querySelector('.ant-anchor-wrapper').getBoundingClientRect();return [...document.querySelectorAll('.ant-anchor-link-title')].map(n=>{const b=n.getBoundingClientRect();return{x:b.x-p.x,y:b.y-p.y}})},{direction,links});
 const expected=render('Anchor',{direction,items:links}).filter(n=>n.name==='Content');for(let k=0;k<3;k++){assert(Math.abs(expected[k].x-actual[k].x)<1,`Anchor ${direction} x ${k}: ${expected[k].x}/${actual[k].x}`);assert(Math.abs(expected[k].y-actual[k].y)<1,`Anchor ${direction} y ${k}: ${expected[k].y}/${actual[k].y}`);}checks++;
}
const nestedAnchorItems=[{href:'#basic',title:'Basic demo'},{href:'#static',title:'Static demo'},{href:'#api',title:'API',children:[{href:'#anchor',title:'Anchor Props'},{href:'#link',title:'Link Props'}]}];
assert.equal(render('Anchor',{items:[{href:'#one',title:'One'},{href:'#two',title:'Two'}]},400,160).find(n=>n.name==='Anchor rail').height,60,'Vertical Anchor rail must follow its links instead of filling an oversized instance');
assert.equal(render('Anchor',{items:[{href:'#one',title:'One'},{href:'#two',title:'Two'}]},400,160).find(n=>n.name==='Active anchor indicator').y,8,'Anchor without activeHref must select its first item');
const nestedActual=await page.evaluate(async items=>{ReactDOM.render(React.createElement(antd.ConfigProvider,{theme:{token:{fontFamily:'Inter'}}},React.createElement(antd.Anchor,{items,getCurrentAnchor:()=> '#basic',style:{width:400}})),document.getElementById('root'));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const p=document.querySelector('.ant-anchor-wrapper').getBoundingClientRect();return [...document.querySelectorAll('.ant-anchor-link-title')].map(n=>{const b=n.getBoundingClientRect();return{x:b.x-p.x,y:b.y-p.y,w:b.width}})},nestedAnchorItems);
const nestedExpected=render('Anchor',{items:nestedAnchorItems,activeHref:'#basic'},400,149).filter(n=>n.name==='Content');nestedExpected.forEach((n,k)=>{assert.equal(n.x,nestedActual[k].x);assert.equal(n.y,nestedActual[k].y);assert(Math.abs(n.width-nestedActual[k].w)<1);});checks++;
const anchorSemantic=render('Anchor',{items:[{href:'#1',title:'Part 1'}],activeHref:'#1',styles:{root:{backgroundColor:'#fffbe680'},itemTitle:{color:'#8f87f1'},indicator:{backgroundColor:'#ff4d4f'}}},400,200);
assert.equal(anchorSemantic.find(n=>n.name==='Anchor root').fill,'#fffbe680');assert.equal(anchorSemantic.find(n=>n.name==='Content').fill,'#8f87f1');assert.equal(anchorSemantic.find(n=>n.name==='Active anchor indicator').fill,'#ff4d4f');
const breadcrumbIconItems=[{title:'',href:'',icon:'HomeOutlined'},{title:'Application List',href:'',icon:'UserOutlined'},{title:'Dashboard',href:'',icon:'LineChartOutlined'},{title:'Application'}];
const breadcrumbIconExpected=render('Breadcrumb',{items:breadcrumbIconItems},774,22),breadcrumbIcons=breadcrumbIconExpected.filter(n=>n.name==='Icon');
assert.equal(breadcrumbIcons.length,3);assert(breadcrumbIcons.every(n=>n.inputs.color==='#00000073'&&n.inputs.fontSize===14));
const breadcrumbIconActual=await page.evaluate(async ()=>{const svg=()=>React.createElement('svg',{viewBox:'0 0 24 24',width:'1em',height:'1em'},React.createElement('path',{d:'M3 3h18v18H3z'}));const items=[{href:'',title:svg()},{href:'',title:React.createElement(React.Fragment,null,svg(),React.createElement('span',null,'Application List'))},{href:'',title:React.createElement(React.Fragment,null,svg(),React.createElement('span',null,'Dashboard'))},{title:'Application'}];ReactDOM.render(React.createElement(antd.ConfigProvider,{theme:{token:{fontFamily:'Inter'}}},React.createElement(antd.Breadcrumb,{items})),document.getElementById('root'));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const root=document.querySelector('.ant-breadcrumb').getBoundingClientRect();return [...document.querySelectorAll('.ant-breadcrumb-link svg')].map(n=>{const b=n.getBoundingClientRect(),s=getComputedStyle(n);return{x:b.x-root.x,y:b.y-root.y,w:b.width,h:b.height,color:s.color};});});
breadcrumbIcons.forEach((n,k)=>{assert(Math.abs(n.x-breadcrumbIconActual[k].x)<1,`Breadcrumb icon x ${k}: ${n.x}/${breadcrumbIconActual[k].x}`);assert(Math.abs(n.y-breadcrumbIconActual[k].y)<1,`Breadcrumb icon y ${k}: ${n.y}/${breadcrumbIconActual[k].y}`);assert.equal(breadcrumbIconActual[k].w,14);assert.equal(breadcrumbIconActual[k].h,14);assert.equal(breadcrumbIconActual[k].color,'rgba(0, 0, 0, 0.45)');});checks++;
for(const styles of [breadcrumbStyles,{root:{border:'1px solid #F5EFFF',padding:8,borderRadius:4},item:{color:'#8F87F1'},separator:{color:'#00000073'}}]){
 const list=styles.item.color==='#1890ff'?[{title:'Ant Design'},{title:'Component',href:''}]:[{title:'Ant Design'},{title:'Component',href:''},{title:'Breadcrumb'}];
 const actual=await page.evaluate(async ({styles,list})=>{ReactDOM.render(React.createElement(antd.ConfigProvider,{theme:{token:{fontFamily:'Inter'}}},React.createElement(antd.Breadcrumb,{items:list,styles,style:{width:774}})),document.getElementById('root'));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const root=document.querySelector('.ant-breadcrumb'),r=root.getBoundingClientRect(),s=getComputedStyle(root),els=[...root.querySelectorAll('.ant-breadcrumb-link')],item=root.querySelector('.ant-breadcrumb-item'),ib=item.getBoundingClientRect();return{w:r.width,h:r.height,padding:s.padding,borderRadius:s.borderRadius,itemX:ib.x-r.x,itemY:ib.y-r.y,itemColors:els.map(n=>getComputedStyle(n).color)};},{styles,list});
 const expected=render('Breadcrumb',{items:list,styles},774,40),surface=expected.find(n=>n.name==='Breadcrumb root'),contents=expected.filter(n=>n.name==='Content');assert.deepEqual([actual.w,actual.h,actual.padding,actual.borderRadius],[surface.width,surface.height,'8px','4px']);assert.equal(actual.itemX,contents[0].x);assert.equal(actual.itemY,contents[0].y);assert.equal(actual.itemColors[0],styles.item.color==='#1890ff'?'rgb(24, 144, 255)':'rgb(143, 135, 241)');assert.equal(actual.itemColors[1],'rgba(0, 0, 0, 0.45)');assert.equal(contents[2].fill,'#00000073');checks++;
}
for(const size of ['middle','small']){
 const actual=await page.evaluate(async ({size,items})=>{ReactDOM.render(React.createElement(antd.ConfigProvider,{theme:{token:{fontFamily:'Inter'}}},React.createElement(antd.Steps,{size,current:1,items,style:{width:740}})),document.getElementById('root'));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const p=document.querySelector('.ant-steps').getBoundingClientRect();return [...document.querySelectorAll('.ant-steps-item-icon')].map(n=>{const b=n.getBoundingClientRect();return{x:b.x-p.x,y:b.y-p.y,w:b.width}})},{size,items});const expected=render('Steps',{size,current:1,items}).filter(n=>n.name==='Step icon');expected.forEach((n,k)=>{assert(Math.abs(n.x-actual[k].x)<4,`Steps ${size} x ${k}: ${n.x}/${actual[k].x}`);assert.equal(n.width,actual[k].w);});checks++;
}
console.log(`PASS: ${instances.length} independent canvas instances, ${snapshots} Navigation render snapshots, ${checks} Ant Design browser geometry comparisons, state changes and nested Menu/Select instances.`);
}finally{await browser.close();}
